//
// Copyright (c) 2025 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: osac/private/v1/compute_instance_groups_service.proto

package privatev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ComputeInstanceGroups_List_FullMethodName   = "/osac.private.v1.ComputeInstanceGroups/List"
	ComputeInstanceGroups_Get_FullMethodName    = "/osac.private.v1.ComputeInstanceGroups/Get"
	ComputeInstanceGroups_Create_FullMethodName = "/osac.private.v1.ComputeInstanceGroups/Create"
	ComputeInstanceGroups_Delete_FullMethodName = "/osac.private.v1.ComputeInstanceGroups/Delete"
	ComputeInstanceGroups_Update_FullMethodName = "/osac.private.v1.ComputeInstanceGroups/Update"
	ComputeInstanceGroups_Signal_FullMethodName = "/osac.private.v1.ComputeInstanceGroups/Signal"
)

// ComputeInstanceGroupsClient is the client API for ComputeInstanceGroups service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ComputeInstanceGroupsClient interface {
	List(ctx context.Context, in *ComputeInstanceGroupsListRequest, opts ...grpc.CallOption) (*ComputeInstanceGroupsListResponse, error)
	Get(ctx context.Context, in *ComputeInstanceGroupsGetRequest, opts ...grpc.CallOption) (*ComputeInstanceGroupsGetResponse, error)
	Create(ctx context.Context, in *ComputeInstanceGroupsCreateRequest, opts ...grpc.CallOption) (*ComputeInstanceGroupsCreateResponse, error)
	Delete(ctx context.Context, in *ComputeInstanceGroupsDeleteRequest, opts ...grpc.CallOption) (*ComputeInstanceGroupsDeleteResponse, error)
	Update(ctx context.Context, in *ComputeInstanceGroupsUpdateRequest, opts ...grpc.CallOption) (*ComputeInstanceGroupsUpdateResponse, error)
	Signal(ctx context.Context, in *ComputeInstanceGroupsSignalRequest, opts ...grpc.CallOption) (*ComputeInstanceGroupsSignalResponse, error)
}

type computeInstanceGroupsClient struct {
	cc grpc.ClientConnInterface
}

func NewComputeInstanceGroupsClient(cc grpc.ClientConnInterface) ComputeInstanceGroupsClient {
	return &computeInstanceGroupsClient{cc}
}

func (c *computeInstanceGroupsClient) List(ctx context.Context, in *ComputeInstanceGroupsListRequest, opts ...grpc.CallOption) (*ComputeInstanceGroupsListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ComputeInstanceGroupsListResponse)
	err := c.cc.Invoke(ctx, ComputeInstanceGroups_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *computeInstanceGroupsClient) Get(ctx context.Context, in *ComputeInstanceGroupsGetRequest, opts ...grpc.CallOption) (*ComputeInstanceGroupsGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ComputeInstanceGroupsGetResponse)
	err := c.cc.Invoke(ctx, ComputeInstanceGroups_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *computeInstanceGroupsClient) Create(ctx context.Context, in *ComputeInstanceGroupsCreateRequest, opts ...grpc.CallOption) (*ComputeInstanceGroupsCreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ComputeInstanceGroupsCreateResponse)
	err := c.cc.Invoke(ctx, ComputeInstanceGroups_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *computeInstanceGroupsClient) Delete(ctx context.Context, in *ComputeInstanceGroupsDeleteRequest, opts ...grpc.CallOption) (*ComputeInstanceGroupsDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ComputeInstanceGroupsDeleteResponse)
	err := c.cc.Invoke(ctx, ComputeInstanceGroups_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *computeInstanceGroupsClient) Update(ctx context.Context, in *ComputeInstanceGroupsUpdateRequest, opts ...grpc.CallOption) (*ComputeInstanceGroupsUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ComputeInstanceGroupsUpdateResponse)
	err := c.cc.Invoke(ctx, ComputeInstanceGroups_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *computeInstanceGroupsClient) Signal(ctx context.Context, in *ComputeInstanceGroupsSignalRequest, opts ...grpc.CallOption) (*ComputeInstanceGroupsSignalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ComputeInstanceGroupsSignalResponse)
	err := c.cc.Invoke(ctx, ComputeInstanceGroups_Signal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ComputeInstanceGroupsServer is the server API for ComputeInstanceGroups service.
// All implementations must embed UnimplementedComputeInstanceGroupsServer
// for forward compatibility.
type ComputeInstanceGroupsServer interface {
	List(context.Context, *ComputeInstanceGroupsListRequest) (*ComputeInstanceGroupsListResponse, error)
	Get(context.Context, *ComputeInstanceGroupsGetRequest) (*ComputeInstanceGroupsGetResponse, error)
	Create(context.Context, *ComputeInstanceGroupsCreateRequest) (*ComputeInstanceGroupsCreateResponse, error)
	Delete(context.Context, *ComputeInstanceGroupsDeleteRequest) (*ComputeInstanceGroupsDeleteResponse, error)
	Update(context.Context, *ComputeInstanceGroupsUpdateRequest) (*ComputeInstanceGroupsUpdateResponse, error)
	Signal(context.Context, *ComputeInstanceGroupsSignalRequest) (*ComputeInstanceGroupsSignalResponse, error)
	mustEmbedUnimplementedComputeInstanceGroupsServer()
}

// UnimplementedComputeInstanceGroupsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedComputeInstanceGroupsServer struct{}

func (UnimplementedComputeInstanceGroupsServer) List(context.Context, *ComputeInstanceGroupsListRequest) (*ComputeInstanceGroupsListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedComputeInstanceGroupsServer) Get(context.Context, *ComputeInstanceGroupsGetRequest) (*ComputeInstanceGroupsGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedComputeInstanceGroupsServer) Create(context.Context, *ComputeInstanceGroupsCreateRequest) (*ComputeInstanceGroupsCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedComputeInstanceGroupsServer) Delete(context.Context, *ComputeInstanceGroupsDeleteRequest) (*ComputeInstanceGroupsDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedComputeInstanceGroupsServer) Update(context.Context, *ComputeInstanceGroupsUpdateRequest) (*ComputeInstanceGroupsUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedComputeInstanceGroupsServer) Signal(context.Context, *ComputeInstanceGroupsSignalRequest) (*ComputeInstanceGroupsSignalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Signal not implemented")
}
func (UnimplementedComputeInstanceGroupsServer) mustEmbedUnimplementedComputeInstanceGroupsServer() {}
func (UnimplementedComputeInstanceGroupsServer) testEmbeddedByValue()                               {}

// UnsafeComputeInstanceGroupsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ComputeInstanceGroupsServer will
// result in compilation errors.
type UnsafeComputeInstanceGroupsServer interface {
	mustEmbedUnimplementedComputeInstanceGroupsServer()
}

func RegisterComputeInstanceGroupsServer(s grpc.ServiceRegistrar, srv ComputeInstanceGroupsServer) {
	// If the following call pancis, it indicates UnimplementedComputeInstanceGroupsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ComputeInstanceGroups_ServiceDesc, srv)
}

func _ComputeInstanceGroups_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ComputeInstanceGroupsListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputeInstanceGroupsServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComputeInstanceGroups_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputeInstanceGroupsServer).List(ctx, req.(*ComputeInstanceGroupsListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComputeInstanceGroups_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ComputeInstanceGroupsGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputeInstanceGroupsServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComputeInstanceGroups_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputeInstanceGroupsServer).Get(ctx, req.(*ComputeInstanceGroupsGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComputeInstanceGroups_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ComputeInstanceGroupsCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputeInstanceGroupsServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComputeInstanceGroups_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputeInstanceGroupsServer).Create(ctx, req.(*ComputeInstanceGroupsCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComputeInstanceGroups_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ComputeInstanceGroupsDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputeInstanceGroupsServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComputeInstanceGroups_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputeInstanceGroupsServer).Delete(ctx, req.(*ComputeInstanceGroupsDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComputeInstanceGroups_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ComputeInstanceGroupsUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputeInstanceGroupsServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComputeInstanceGroups_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputeInstanceGroupsServer).Update(ctx, req.(*ComputeInstanceGroupsUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComputeInstanceGroups_Signal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ComputeInstanceGroupsSignalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputeInstanceGroupsServer).Signal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComputeInstanceGroups_Signal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputeInstanceGroupsServer).Signal(ctx, req.(*ComputeInstanceGroupsSignalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ComputeInstanceGroups_ServiceDesc is the grpc.ServiceDesc for ComputeInstanceGroups service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ComputeInstanceGroups_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "osac.private.v1.ComputeInstanceGroups",
	HandlerType: (*ComputeInstanceGroupsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _ComputeInstanceGroups_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _ComputeInstanceGroups_Get_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _ComputeInstanceGroups_Create_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ComputeInstanceGroups_Delete_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ComputeInstanceGroups_Update_Handler,
		},
		{
			MethodName: "Signal",
			Handler:    _ComputeInstanceGroups_Signal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "osac/private/v1/compute_instance_groups_service.proto",
}
