//
// Copyright (c) 2026 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: osac/private/v1/compute_instance_group_type.proto

//go:build protoopaque

package privatev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Lifecycle states for ComputeInstanceGroup resources.
type ComputeInstanceGroupState int32

const (
	// State is unknown or has not been determined yet.
	ComputeInstanceGroupState_COMPUTE_INSTANCE_GROUP_STATE_UNSPECIFIED ComputeInstanceGroupState = 0
	// The compute instance group is being initialized and is not yet ready.
	ComputeInstanceGroupState_COMPUTE_INSTANCE_GROUP_STATE_PENDING ComputeInstanceGroupState = 1
	// All desired replicas are running and the group is fully operational.
	ComputeInstanceGroupState_COMPUTE_INSTANCE_GROUP_STATE_READY ComputeInstanceGroupState = 2
	// The group is scaling up or down and has not yet reached the desired replica count.
	ComputeInstanceGroupState_COMPUTE_INSTANCE_GROUP_STATE_SCALING ComputeInstanceGroupState = 3
	// The compute instance group has encountered an error and cannot reach the desired state.
	ComputeInstanceGroupState_COMPUTE_INSTANCE_GROUP_STATE_FAILED ComputeInstanceGroupState = 4
)

// Enum value maps for ComputeInstanceGroupState.
var (
	ComputeInstanceGroupState_name = map[int32]string{
		0: "COMPUTE_INSTANCE_GROUP_STATE_UNSPECIFIED",
		1: "COMPUTE_INSTANCE_GROUP_STATE_PENDING",
		2: "COMPUTE_INSTANCE_GROUP_STATE_READY",
		3: "COMPUTE_INSTANCE_GROUP_STATE_SCALING",
		4: "COMPUTE_INSTANCE_GROUP_STATE_FAILED",
	}
	ComputeInstanceGroupState_value = map[string]int32{
		"COMPUTE_INSTANCE_GROUP_STATE_UNSPECIFIED": 0,
		"COMPUTE_INSTANCE_GROUP_STATE_PENDING":     1,
		"COMPUTE_INSTANCE_GROUP_STATE_READY":       2,
		"COMPUTE_INSTANCE_GROUP_STATE_SCALING":     3,
		"COMPUTE_INSTANCE_GROUP_STATE_FAILED":      4,
	}
)

func (x ComputeInstanceGroupState) Enum() *ComputeInstanceGroupState {
	p := new(ComputeInstanceGroupState)
	*p = x
	return p
}

func (x ComputeInstanceGroupState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ComputeInstanceGroupState) Descriptor() protoreflect.EnumDescriptor {
	return file_osac_private_v1_compute_instance_group_type_proto_enumTypes[0].Descriptor()
}

func (ComputeInstanceGroupState) Type() protoreflect.EnumType {
	return &file_osac_private_v1_compute_instance_group_type_proto_enumTypes[0]
}

func (x ComputeInstanceGroupState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// A ComputeInstanceGroup manages a scaled set of identical ComputeInstances with placement semantics.
// Scaling up increases replicas and creates new ComputeInstances. Scaling down removes instances
// (last created first).
type ComputeInstanceGroup struct {
	state               protoimpl.MessageState      `protogen:"opaque.v1"`
	xxx_hidden_Id       string                      `protobuf:"bytes,1,opt,name=id,proto3"`
	xxx_hidden_Metadata *Metadata                   `protobuf:"bytes,2,opt,name=metadata,proto3"`
	xxx_hidden_Spec     *ComputeInstanceGroupSpec   `protobuf:"bytes,3,opt,name=spec,proto3"`
	xxx_hidden_Status   *ComputeInstanceGroupStatus `protobuf:"bytes,4,opt,name=status,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ComputeInstanceGroup) Reset() {
	*x = ComputeInstanceGroup{}
	mi := &file_osac_private_v1_compute_instance_group_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeInstanceGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeInstanceGroup) ProtoMessage() {}

func (x *ComputeInstanceGroup) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_compute_instance_group_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ComputeInstanceGroup) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *ComputeInstanceGroup) GetMetadata() *Metadata {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return nil
}

func (x *ComputeInstanceGroup) GetSpec() *ComputeInstanceGroupSpec {
	if x != nil {
		return x.xxx_hidden_Spec
	}
	return nil
}

func (x *ComputeInstanceGroup) GetStatus() *ComputeInstanceGroupStatus {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return nil
}

func (x *ComputeInstanceGroup) SetId(v string) {
	x.xxx_hidden_Id = v
}

func (x *ComputeInstanceGroup) SetMetadata(v *Metadata) {
	x.xxx_hidden_Metadata = v
}

func (x *ComputeInstanceGroup) SetSpec(v *ComputeInstanceGroupSpec) {
	x.xxx_hidden_Spec = v
}

func (x *ComputeInstanceGroup) SetStatus(v *ComputeInstanceGroupStatus) {
	x.xxx_hidden_Status = v
}

func (x *ComputeInstanceGroup) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Metadata != nil
}

func (x *ComputeInstanceGroup) HasSpec() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Spec != nil
}

func (x *ComputeInstanceGroup) HasStatus() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Status != nil
}

func (x *ComputeInstanceGroup) ClearMetadata() {
	x.xxx_hidden_Metadata = nil
}

func (x *ComputeInstanceGroup) ClearSpec() {
	x.xxx_hidden_Spec = nil
}

func (x *ComputeInstanceGroup) ClearStatus() {
	x.xxx_hidden_Status = nil
}

type ComputeInstanceGroup_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Unique identifier of the compute instance group.
	Id string
	// Metadata of the compute instance group.
	Metadata *Metadata
	// Desired state of the compute instance group.
	Spec *ComputeInstanceGroupSpec
	// Current state of the compute instance group.
	Status *ComputeInstanceGroupStatus
}

func (b0 ComputeInstanceGroup_builder) Build() *ComputeInstanceGroup {
	m0 := &ComputeInstanceGroup{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Metadata = b.Metadata
	x.xxx_hidden_Spec = b.Spec
	x.xxx_hidden_Status = b.Status
	return m0
}

type ComputeInstanceGroupSpec struct {
	state                           protoimpl.MessageState               `protogen:"opaque.v1"`
	xxx_hidden_ComputeInstanceClass string                               `protobuf:"bytes,1,opt,name=compute_instance_class,json=computeInstanceClass,proto3"`
	xxx_hidden_Replicas             int32                                `protobuf:"varint,2,opt,name=replicas,proto3"`
	xxx_hidden_ImageRef             *string                              `protobuf:"bytes,3,opt,name=image_ref,json=imageRef,proto3,oneof"`
	xxx_hidden_SshKeyRefs           []string                             `protobuf:"bytes,4,rep,name=ssh_key_refs,json=sshKeyRefs,proto3"`
	xxx_hidden_Subnet               *string                              `protobuf:"bytes,5,opt,name=subnet,proto3,oneof"`
	xxx_hidden_SecurityGroups       []string                             `protobuf:"bytes,6,rep,name=security_groups,json=securityGroups,proto3"`
	xxx_hidden_UserData             *string                              `protobuf:"bytes,7,opt,name=user_data,json=userData,proto3,oneof"`
	xxx_hidden_Region               *string                              `protobuf:"bytes,8,opt,name=region,proto3,oneof"`
	xxx_hidden_PlacementPolicy      *ComputeInstanceGroupPlacementPolicy `protobuf:"bytes,9,opt,name=placement_policy,json=placementPolicy,proto3,oneof"`
	XXX_raceDetectHookData          protoimpl.RaceDetectHookData
	XXX_presence                    [1]uint32
	unknownFields                   protoimpl.UnknownFields
	sizeCache                       protoimpl.SizeCache
}

func (x *ComputeInstanceGroupSpec) Reset() {
	*x = ComputeInstanceGroupSpec{}
	mi := &file_osac_private_v1_compute_instance_group_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeInstanceGroupSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeInstanceGroupSpec) ProtoMessage() {}

func (x *ComputeInstanceGroupSpec) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_compute_instance_group_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ComputeInstanceGroupSpec) GetComputeInstanceClass() string {
	if x != nil {
		return x.xxx_hidden_ComputeInstanceClass
	}
	return ""
}

func (x *ComputeInstanceGroupSpec) GetReplicas() int32 {
	if x != nil {
		return x.xxx_hidden_Replicas
	}
	return 0
}

func (x *ComputeInstanceGroupSpec) GetImageRef() string {
	if x != nil {
		if x.xxx_hidden_ImageRef != nil {
			return *x.xxx_hidden_ImageRef
		}
		return ""
	}
	return ""
}

func (x *ComputeInstanceGroupSpec) GetSshKeyRefs() []string {
	if x != nil {
		return x.xxx_hidden_SshKeyRefs
	}
	return nil
}

func (x *ComputeInstanceGroupSpec) GetSubnet() string {
	if x != nil {
		if x.xxx_hidden_Subnet != nil {
			return *x.xxx_hidden_Subnet
		}
		return ""
	}
	return ""
}

func (x *ComputeInstanceGroupSpec) GetSecurityGroups() []string {
	if x != nil {
		return x.xxx_hidden_SecurityGroups
	}
	return nil
}

func (x *ComputeInstanceGroupSpec) GetUserData() string {
	if x != nil {
		if x.xxx_hidden_UserData != nil {
			return *x.xxx_hidden_UserData
		}
		return ""
	}
	return ""
}

func (x *ComputeInstanceGroupSpec) GetRegion() string {
	if x != nil {
		if x.xxx_hidden_Region != nil {
			return *x.xxx_hidden_Region
		}
		return ""
	}
	return ""
}

func (x *ComputeInstanceGroupSpec) GetPlacementPolicy() *ComputeInstanceGroupPlacementPolicy {
	if x != nil {
		return x.xxx_hidden_PlacementPolicy
	}
	return nil
}

func (x *ComputeInstanceGroupSpec) SetComputeInstanceClass(v string) {
	x.xxx_hidden_ComputeInstanceClass = v
}

func (x *ComputeInstanceGroupSpec) SetReplicas(v int32) {
	x.xxx_hidden_Replicas = v
}

func (x *ComputeInstanceGroupSpec) SetImageRef(v string) {
	x.xxx_hidden_ImageRef = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 9)
}

func (x *ComputeInstanceGroupSpec) SetSshKeyRefs(v []string) {
	x.xxx_hidden_SshKeyRefs = v
}

func (x *ComputeInstanceGroupSpec) SetSubnet(v string) {
	x.xxx_hidden_Subnet = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 9)
}

func (x *ComputeInstanceGroupSpec) SetSecurityGroups(v []string) {
	x.xxx_hidden_SecurityGroups = v
}

func (x *ComputeInstanceGroupSpec) SetUserData(v string) {
	x.xxx_hidden_UserData = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 9)
}

func (x *ComputeInstanceGroupSpec) SetRegion(v string) {
	x.xxx_hidden_Region = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 9)
}

func (x *ComputeInstanceGroupSpec) SetPlacementPolicy(v *ComputeInstanceGroupPlacementPolicy) {
	x.xxx_hidden_PlacementPolicy = v
}

func (x *ComputeInstanceGroupSpec) HasImageRef() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ComputeInstanceGroupSpec) HasSubnet() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *ComputeInstanceGroupSpec) HasUserData() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *ComputeInstanceGroupSpec) HasRegion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *ComputeInstanceGroupSpec) HasPlacementPolicy() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_PlacementPolicy != nil
}

func (x *ComputeInstanceGroupSpec) ClearImageRef() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_ImageRef = nil
}

func (x *ComputeInstanceGroupSpec) ClearSubnet() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Subnet = nil
}

func (x *ComputeInstanceGroupSpec) ClearUserData() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_UserData = nil
}

func (x *ComputeInstanceGroupSpec) ClearRegion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_Region = nil
}

func (x *ComputeInstanceGroupSpec) ClearPlacementPolicy() {
	x.xxx_hidden_PlacementPolicy = nil
}

type ComputeInstanceGroupSpec_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Reference to the ComputeInstanceClass for all instances in this group.
	ComputeInstanceClass string
	// Desired number of ComputeInstances in the group.
	Replicas int32
	// Reference to an Image resource by name.
	ImageRef *string
	// References to SSHKey resources by name.
	SshKeyRefs []string
	// Subnet ID for network attachment.
	Subnet *string
	// SecurityGroup IDs for security policies.
	SecurityGroups []string
	// User data for all instances in the group.
	UserData *string
	// Region narrows template selection within the class.
	Region *string
	// Placement policy for instance distribution.
	PlacementPolicy *ComputeInstanceGroupPlacementPolicy
}

func (b0 ComputeInstanceGroupSpec_builder) Build() *ComputeInstanceGroupSpec {
	m0 := &ComputeInstanceGroupSpec{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ComputeInstanceClass = b.ComputeInstanceClass
	x.xxx_hidden_Replicas = b.Replicas
	if b.ImageRef != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 9)
		x.xxx_hidden_ImageRef = b.ImageRef
	}
	x.xxx_hidden_SshKeyRefs = b.SshKeyRefs
	if b.Subnet != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 9)
		x.xxx_hidden_Subnet = b.Subnet
	}
	x.xxx_hidden_SecurityGroups = b.SecurityGroups
	if b.UserData != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 9)
		x.xxx_hidden_UserData = b.UserData
	}
	if b.Region != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 9)
		x.xxx_hidden_Region = b.Region
	}
	x.xxx_hidden_PlacementPolicy = b.PlacementPolicy
	return m0
}

// Placement policy controls how instances are distributed across infrastructure.
type ComputeInstanceGroupPlacementPolicy struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Strategy    string                 `protobuf:"bytes,1,opt,name=strategy,proto3"`
	xxx_hidden_AffinityKey *string                `protobuf:"bytes,2,opt,name=affinity_key,json=affinityKey,proto3,oneof"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ComputeInstanceGroupPlacementPolicy) Reset() {
	*x = ComputeInstanceGroupPlacementPolicy{}
	mi := &file_osac_private_v1_compute_instance_group_type_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeInstanceGroupPlacementPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeInstanceGroupPlacementPolicy) ProtoMessage() {}

func (x *ComputeInstanceGroupPlacementPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_compute_instance_group_type_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ComputeInstanceGroupPlacementPolicy) GetStrategy() string {
	if x != nil {
		return x.xxx_hidden_Strategy
	}
	return ""
}

func (x *ComputeInstanceGroupPlacementPolicy) GetAffinityKey() string {
	if x != nil {
		if x.xxx_hidden_AffinityKey != nil {
			return *x.xxx_hidden_AffinityKey
		}
		return ""
	}
	return ""
}

func (x *ComputeInstanceGroupPlacementPolicy) SetStrategy(v string) {
	x.xxx_hidden_Strategy = v
}

func (x *ComputeInstanceGroupPlacementPolicy) SetAffinityKey(v string) {
	x.xxx_hidden_AffinityKey = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *ComputeInstanceGroupPlacementPolicy) HasAffinityKey() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ComputeInstanceGroupPlacementPolicy) ClearAffinityKey() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_AffinityKey = nil
}

type ComputeInstanceGroupPlacementPolicy_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Strategy for placement: "pack" fills groups before spilling, "spread" distributes across domains.
	Strategy string
	// Host variable name to group by for affinity (e.g. "nvlink_domain", "rack").
	AffinityKey *string
}

func (b0 ComputeInstanceGroupPlacementPolicy_builder) Build() *ComputeInstanceGroupPlacementPolicy {
	m0 := &ComputeInstanceGroupPlacementPolicy{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Strategy = b.Strategy
	if b.AffinityKey != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_AffinityKey = b.AffinityKey
	}
	return m0
}

type ComputeInstanceGroupStatus struct {
	state                    protoimpl.MessageState    `protogen:"opaque.v1"`
	xxx_hidden_State         ComputeInstanceGroupState `protobuf:"varint,1,opt,name=state,proto3,enum=osac.private.v1.ComputeInstanceGroupState"`
	xxx_hidden_ReadyReplicas int32                     `protobuf:"varint,2,opt,name=ready_replicas,json=readyReplicas,proto3"`
	xxx_hidden_Instances     []string                  `protobuf:"bytes,3,rep,name=instances,proto3"`
	xxx_hidden_Message       *string                   `protobuf:"bytes,4,opt,name=message,proto3,oneof"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ComputeInstanceGroupStatus) Reset() {
	*x = ComputeInstanceGroupStatus{}
	mi := &file_osac_private_v1_compute_instance_group_type_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeInstanceGroupStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeInstanceGroupStatus) ProtoMessage() {}

func (x *ComputeInstanceGroupStatus) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_compute_instance_group_type_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ComputeInstanceGroupStatus) GetState() ComputeInstanceGroupState {
	if x != nil {
		return x.xxx_hidden_State
	}
	return ComputeInstanceGroupState_COMPUTE_INSTANCE_GROUP_STATE_UNSPECIFIED
}

func (x *ComputeInstanceGroupStatus) GetReadyReplicas() int32 {
	if x != nil {
		return x.xxx_hidden_ReadyReplicas
	}
	return 0
}

func (x *ComputeInstanceGroupStatus) GetInstances() []string {
	if x != nil {
		return x.xxx_hidden_Instances
	}
	return nil
}

func (x *ComputeInstanceGroupStatus) GetMessage() string {
	if x != nil {
		if x.xxx_hidden_Message != nil {
			return *x.xxx_hidden_Message
		}
		return ""
	}
	return ""
}

func (x *ComputeInstanceGroupStatus) SetState(v ComputeInstanceGroupState) {
	x.xxx_hidden_State = v
}

func (x *ComputeInstanceGroupStatus) SetReadyReplicas(v int32) {
	x.xxx_hidden_ReadyReplicas = v
}

func (x *ComputeInstanceGroupStatus) SetInstances(v []string) {
	x.xxx_hidden_Instances = v
}

func (x *ComputeInstanceGroupStatus) SetMessage(v string) {
	x.xxx_hidden_Message = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *ComputeInstanceGroupStatus) HasMessage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *ComputeInstanceGroupStatus) ClearMessage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Message = nil
}

type ComputeInstanceGroupStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Current lifecycle state of the group.
	State ComputeInstanceGroupState
	// Number of instances that are in RUNNING state.
	ReadyReplicas int32
	// List of ComputeInstance IDs managed by this group.
	Instances []string
	// Human-readable message providing additional details about the current state.
	Message *string
}

func (b0 ComputeInstanceGroupStatus_builder) Build() *ComputeInstanceGroupStatus {
	m0 := &ComputeInstanceGroupStatus{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_State = b.State
	x.xxx_hidden_ReadyReplicas = b.ReadyReplicas
	x.xxx_hidden_Instances = b.Instances
	if b.Message != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_Message = b.Message
	}
	return m0
}

var File_osac_private_v1_compute_instance_group_type_proto protoreflect.FileDescriptor

var file_osac_private_v1_compute_instance_group_type_proto_rawDesc = string([]byte{
	0x0a, 0x31, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x76,
	0x31, 0x2f, 0x63, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x5f, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e,
	0x63, 0x65, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x2e, 0x76, 0x31, 0x1a, 0x23, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61,
	0x74, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe1, 0x01, 0x0a, 0x14, 0x43, 0x6f,
	0x6d, 0x70, 0x75, 0x74, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x35, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76,
	0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52,
	0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x3d, 0x0a, 0x04, 0x73, 0x70, 0x65,
	0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70,
	0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74,
	0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x53, 0x70,
	0x65, 0x63, 0x52, 0x04, 0x73, 0x70, 0x65, 0x63, 0x12, 0x43, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e,
	0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x75,
	0x74, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0xe2, 0x03,
	0x0a, 0x18, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x53, 0x70, 0x65, 0x63, 0x12, 0x34, 0x0a, 0x16, 0x63, 0x6f,
	0x6d, 0x70, 0x75, 0x74, 0x65, 0x5f, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x63,
	0x6c, 0x61, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x14, 0x63, 0x6f, 0x6d, 0x70,
	0x75, 0x74, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73,
	0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x73, 0x12, 0x20, 0x0a, 0x09,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x72, 0x65, 0x66, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x66, 0x88, 0x01, 0x01, 0x12, 0x20,
	0x0a, 0x0c, 0x73, 0x73, 0x68, 0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x72, 0x65, 0x66, 0x73, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x73, 0x68, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x66, 0x73,
	0x12, 0x1b, 0x0a, 0x06, 0x73, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x01, 0x52, 0x06, 0x73, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x88, 0x01, 0x01, 0x12, 0x27, 0x0a,
	0x0f, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73,
	0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0e, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x12, 0x20, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x44, 0x61, 0x74, 0x61, 0x88, 0x01, 0x01, 0x12, 0x1b, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x69,
	0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x48, 0x03, 0x52, 0x06, 0x72, 0x65, 0x67, 0x69,
	0x6f, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x64, 0x0a, 0x10, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x5f, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x34, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x50,
	0x6f, 0x6c, 0x69, 0x63, 0x79, 0x48, 0x04, 0x52, 0x0f, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x88, 0x01, 0x01, 0x42, 0x0c, 0x0a, 0x0a, 0x5f,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x72, 0x65, 0x66, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x73, 0x75,
	0x62, 0x6e, 0x65, 0x74, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x64, 0x61,
	0x74, 0x61, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x42, 0x13, 0x0a,
	0x11, 0x5f, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x70, 0x6f, 0x6c, 0x69,
	0x63, 0x79, 0x22, 0x7a, 0x0a, 0x23, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x49, 0x6e, 0x73,
	0x74, 0x61, 0x6e, 0x63, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x74, 0x72,
	0x61, 0x74, 0x65, 0x67, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x74, 0x72,
	0x61, 0x74, 0x65, 0x67, 0x79, 0x12, 0x26, 0x0a, 0x0c, 0x61, 0x66, 0x66, 0x69, 0x6e, 0x69, 0x74,
	0x79, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x61,
	0x66, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x79, 0x4b, 0x65, 0x79, 0x88, 0x01, 0x01, 0x42, 0x0f, 0x0a,
	0x0d, 0x5f, 0x61, 0x66, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x79, 0x5f, 0x6b, 0x65, 0x79, 0x22, 0xce,
	0x01, 0x0a, 0x1a, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e,
	0x63, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x40, 0x0a,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2a, 0x2e, 0x6f,
	0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43,
	0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12,
	0x25, 0x0a, 0x0e, 0x72, 0x65, 0x61, 0x64, 0x79, 0x5f, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x72, 0x65, 0x61, 0x64, 0x79, 0x52, 0x65,
	0x70, 0x6c, 0x69, 0x63, 0x61, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e,
	0x63, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6e, 0x73, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x73, 0x12, 0x1d, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x88, 0x01, 0x01, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2a,
	0xee, 0x01, 0x0a, 0x19, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x2c, 0x0a,
	0x28, 0x43, 0x4f, 0x4d, 0x50, 0x55, 0x54, 0x45, 0x5f, 0x49, 0x4e, 0x53, 0x54, 0x41, 0x4e, 0x43,
	0x45, 0x5f, 0x47, 0x52, 0x4f, 0x55, 0x50, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x55, 0x4e,
	0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x28, 0x0a, 0x24, 0x43,
	0x4f, 0x4d, 0x50, 0x55, 0x54, 0x45, 0x5f, 0x49, 0x4e, 0x53, 0x54, 0x41, 0x4e, 0x43, 0x45, 0x5f,
	0x47, 0x52, 0x4f, 0x55, 0x50, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x50, 0x45, 0x4e, 0x44,
	0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x26, 0x0a, 0x22, 0x43, 0x4f, 0x4d, 0x50, 0x55, 0x54, 0x45,
	0x5f, 0x49, 0x4e, 0x53, 0x54, 0x41, 0x4e, 0x43, 0x45, 0x5f, 0x47, 0x52, 0x4f, 0x55, 0x50, 0x5f,
	0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x52, 0x45, 0x41, 0x44, 0x59, 0x10, 0x02, 0x12, 0x28, 0x0a,
	0x24, 0x43, 0x4f, 0x4d, 0x50, 0x55, 0x54, 0x45, 0x5f, 0x49, 0x4e, 0x53, 0x54, 0x41, 0x4e, 0x43,
	0x45, 0x5f, 0x47, 0x52, 0x4f, 0x55, 0x50, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x53, 0x43,
	0x41, 0x4c, 0x49, 0x4e, 0x47, 0x10, 0x03, 0x12, 0x27, 0x0a, 0x23, 0x43, 0x4f, 0x4d, 0x50, 0x55,
	0x54, 0x45, 0x5f, 0x49, 0x4e, 0x53, 0x54, 0x41, 0x4e, 0x43, 0x45, 0x5f, 0x47, 0x52, 0x4f, 0x55,
	0x50, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x04,
	0x42, 0xe8, 0x01, 0x0a, 0x13, 0x63, 0x6f, 0x6d, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72,
	0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x42, 0x1d, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74,
	0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x54, 0x79,
	0x70, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x52, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x73, 0x61, 0x63, 0x2d, 0x70, 0x72, 0x6f, 0x6a, 0x65,
	0x63, 0x74, 0x2f, 0x66, 0x75, 0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x2d, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x2f, 0x76, 0x31, 0x3b, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x76, 0x31, 0xa2, 0x02, 0x03,
	0x4f, 0x50, 0x58, 0xaa, 0x02, 0x0f, 0x4f, 0x73, 0x61, 0x63, 0x2e, 0x50, 0x72, 0x69, 0x76, 0x61,
	0x74, 0x65, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x10, 0x4f, 0x73, 0x61, 0x63, 0x5c, 0x50, 0x72, 0x69,
	0x76, 0x61, 0x74, 0x65, 0x5f, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x1c, 0x4f, 0x73, 0x61, 0x63, 0x5c,
	0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x11, 0x4f, 0x73, 0x61, 0x63, 0x3a, 0x3a,
	0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
})

var file_osac_private_v1_compute_instance_group_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_osac_private_v1_compute_instance_group_type_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_osac_private_v1_compute_instance_group_type_proto_goTypes = []any{
	(ComputeInstanceGroupState)(0),              // 0: osac.private.v1.ComputeInstanceGroupState
	(*ComputeInstanceGroup)(nil),                // 1: osac.private.v1.ComputeInstanceGroup
	(*ComputeInstanceGroupSpec)(nil),            // 2: osac.private.v1.ComputeInstanceGroupSpec
	(*ComputeInstanceGroupPlacementPolicy)(nil), // 3: osac.private.v1.ComputeInstanceGroupPlacementPolicy
	(*ComputeInstanceGroupStatus)(nil),          // 4: osac.private.v1.ComputeInstanceGroupStatus
	(*Metadata)(nil),                            // 5: osac.private.v1.Metadata
}
var file_osac_private_v1_compute_instance_group_type_proto_depIdxs = []int32{
	5, // 0: osac.private.v1.ComputeInstanceGroup.metadata:type_name -> osac.private.v1.Metadata
	2, // 1: osac.private.v1.ComputeInstanceGroup.spec:type_name -> osac.private.v1.ComputeInstanceGroupSpec
	4, // 2: osac.private.v1.ComputeInstanceGroup.status:type_name -> osac.private.v1.ComputeInstanceGroupStatus
	3, // 3: osac.private.v1.ComputeInstanceGroupSpec.placement_policy:type_name -> osac.private.v1.ComputeInstanceGroupPlacementPolicy
	0, // 4: osac.private.v1.ComputeInstanceGroupStatus.state:type_name -> osac.private.v1.ComputeInstanceGroupState
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_osac_private_v1_compute_instance_group_type_proto_init() }
func file_osac_private_v1_compute_instance_group_type_proto_init() {
	if File_osac_private_v1_compute_instance_group_type_proto != nil {
		return
	}
	file_osac_private_v1_metadata_type_proto_init()
	file_osac_private_v1_compute_instance_group_type_proto_msgTypes[1].OneofWrappers = []any{}
	file_osac_private_v1_compute_instance_group_type_proto_msgTypes[2].OneofWrappers = []any{}
	file_osac_private_v1_compute_instance_group_type_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_osac_private_v1_compute_instance_group_type_proto_rawDesc), len(file_osac_private_v1_compute_instance_group_type_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_osac_private_v1_compute_instance_group_type_proto_goTypes,
		DependencyIndexes: file_osac_private_v1_compute_instance_group_type_proto_depIdxs,
		EnumInfos:         file_osac_private_v1_compute_instance_group_type_proto_enumTypes,
		MessageInfos:      file_osac_private_v1_compute_instance_group_type_proto_msgTypes,
	}.Build()
	File_osac_private_v1_compute_instance_group_type_proto = out.File
	file_osac_private_v1_compute_instance_group_type_proto_goTypes = nil
	file_osac_private_v1_compute_instance_group_type_proto_depIdxs = nil
}
