//
// Copyright (c) 2025 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: osac/private/v1/compute_instance_classes_service.proto

package privatev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ComputeInstanceClasses_List_FullMethodName   = "/osac.private.v1.ComputeInstanceClasses/List"
	ComputeInstanceClasses_Get_FullMethodName    = "/osac.private.v1.ComputeInstanceClasses/Get"
	ComputeInstanceClasses_Create_FullMethodName = "/osac.private.v1.ComputeInstanceClasses/Create"
	ComputeInstanceClasses_Update_FullMethodName = "/osac.private.v1.ComputeInstanceClasses/Update"
	ComputeInstanceClasses_Delete_FullMethodName = "/osac.private.v1.ComputeInstanceClasses/Delete"
	ComputeInstanceClasses_Signal_FullMethodName = "/osac.private.v1.ComputeInstanceClasses/Signal"
)

// ComputeInstanceClassesClient is the client API for ComputeInstanceClasses service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ComputeInstanceClassesClient interface {
	// Retrieves the list of compute instance classes.
	List(ctx context.Context, in *ComputeInstanceClassesListRequest, opts ...grpc.CallOption) (*ComputeInstanceClassesListResponse, error)
	// Retrieves the details of one specific compute instance class.
	Get(ctx context.Context, in *ComputeInstanceClassesGetRequest, opts ...grpc.CallOption) (*ComputeInstanceClassesGetResponse, error)
	// Creates a new compute instance class.
	Create(ctx context.Context, in *ComputeInstanceClassesCreateRequest, opts ...grpc.CallOption) (*ComputeInstanceClassesCreateResponse, error)
	// Updates an existing compute instance class.
	Update(ctx context.Context, in *ComputeInstanceClassesUpdateRequest, opts ...grpc.CallOption) (*ComputeInstanceClassesUpdateResponse, error)
	// Deletes a compute instance class.
	Delete(ctx context.Context, in *ComputeInstanceClassesDeleteRequest, opts ...grpc.CallOption) (*ComputeInstanceClassesDeleteResponse, error)
	// Indicates that something changed in the object or the system that may require reconciling the object.
	Signal(ctx context.Context, in *ComputeInstanceClassesSignalRequest, opts ...grpc.CallOption) (*ComputeInstanceClassesSignalResponse, error)
}

type computeInstanceClassesClient struct {
	cc grpc.ClientConnInterface
}

func NewComputeInstanceClassesClient(cc grpc.ClientConnInterface) ComputeInstanceClassesClient {
	return &computeInstanceClassesClient{cc}
}

func (c *computeInstanceClassesClient) List(ctx context.Context, in *ComputeInstanceClassesListRequest, opts ...grpc.CallOption) (*ComputeInstanceClassesListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ComputeInstanceClassesListResponse)
	err := c.cc.Invoke(ctx, ComputeInstanceClasses_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *computeInstanceClassesClient) Get(ctx context.Context, in *ComputeInstanceClassesGetRequest, opts ...grpc.CallOption) (*ComputeInstanceClassesGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ComputeInstanceClassesGetResponse)
	err := c.cc.Invoke(ctx, ComputeInstanceClasses_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *computeInstanceClassesClient) Create(ctx context.Context, in *ComputeInstanceClassesCreateRequest, opts ...grpc.CallOption) (*ComputeInstanceClassesCreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ComputeInstanceClassesCreateResponse)
	err := c.cc.Invoke(ctx, ComputeInstanceClasses_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *computeInstanceClassesClient) Update(ctx context.Context, in *ComputeInstanceClassesUpdateRequest, opts ...grpc.CallOption) (*ComputeInstanceClassesUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ComputeInstanceClassesUpdateResponse)
	err := c.cc.Invoke(ctx, ComputeInstanceClasses_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *computeInstanceClassesClient) Delete(ctx context.Context, in *ComputeInstanceClassesDeleteRequest, opts ...grpc.CallOption) (*ComputeInstanceClassesDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ComputeInstanceClassesDeleteResponse)
	err := c.cc.Invoke(ctx, ComputeInstanceClasses_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *computeInstanceClassesClient) Signal(ctx context.Context, in *ComputeInstanceClassesSignalRequest, opts ...grpc.CallOption) (*ComputeInstanceClassesSignalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ComputeInstanceClassesSignalResponse)
	err := c.cc.Invoke(ctx, ComputeInstanceClasses_Signal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ComputeInstanceClassesServer is the server API for ComputeInstanceClasses service.
// All implementations must embed UnimplementedComputeInstanceClassesServer
// for forward compatibility.
type ComputeInstanceClassesServer interface {
	// Retrieves the list of compute instance classes.
	List(context.Context, *ComputeInstanceClassesListRequest) (*ComputeInstanceClassesListResponse, error)
	// Retrieves the details of one specific compute instance class.
	Get(context.Context, *ComputeInstanceClassesGetRequest) (*ComputeInstanceClassesGetResponse, error)
	// Creates a new compute instance class.
	Create(context.Context, *ComputeInstanceClassesCreateRequest) (*ComputeInstanceClassesCreateResponse, error)
	// Updates an existing compute instance class.
	Update(context.Context, *ComputeInstanceClassesUpdateRequest) (*ComputeInstanceClassesUpdateResponse, error)
	// Deletes a compute instance class.
	Delete(context.Context, *ComputeInstanceClassesDeleteRequest) (*ComputeInstanceClassesDeleteResponse, error)
	// Indicates that something changed in the object or the system that may require reconciling the object.
	Signal(context.Context, *ComputeInstanceClassesSignalRequest) (*ComputeInstanceClassesSignalResponse, error)
	mustEmbedUnimplementedComputeInstanceClassesServer()
}

// UnimplementedComputeInstanceClassesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedComputeInstanceClassesServer struct{}

func (UnimplementedComputeInstanceClassesServer) List(context.Context, *ComputeInstanceClassesListRequest) (*ComputeInstanceClassesListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedComputeInstanceClassesServer) Get(context.Context, *ComputeInstanceClassesGetRequest) (*ComputeInstanceClassesGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedComputeInstanceClassesServer) Create(context.Context, *ComputeInstanceClassesCreateRequest) (*ComputeInstanceClassesCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedComputeInstanceClassesServer) Update(context.Context, *ComputeInstanceClassesUpdateRequest) (*ComputeInstanceClassesUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedComputeInstanceClassesServer) Delete(context.Context, *ComputeInstanceClassesDeleteRequest) (*ComputeInstanceClassesDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedComputeInstanceClassesServer) Signal(context.Context, *ComputeInstanceClassesSignalRequest) (*ComputeInstanceClassesSignalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Signal not implemented")
}
func (UnimplementedComputeInstanceClassesServer) mustEmbedUnimplementedComputeInstanceClassesServer() {
}
func (UnimplementedComputeInstanceClassesServer) testEmbeddedByValue() {}

// UnsafeComputeInstanceClassesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ComputeInstanceClassesServer will
// result in compilation errors.
type UnsafeComputeInstanceClassesServer interface {
	mustEmbedUnimplementedComputeInstanceClassesServer()
}

func RegisterComputeInstanceClassesServer(s grpc.ServiceRegistrar, srv ComputeInstanceClassesServer) {
	// If the following call pancis, it indicates UnimplementedComputeInstanceClassesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ComputeInstanceClasses_ServiceDesc, srv)
}

func _ComputeInstanceClasses_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ComputeInstanceClassesListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputeInstanceClassesServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComputeInstanceClasses_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputeInstanceClassesServer).List(ctx, req.(*ComputeInstanceClassesListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComputeInstanceClasses_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ComputeInstanceClassesGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputeInstanceClassesServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComputeInstanceClasses_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputeInstanceClassesServer).Get(ctx, req.(*ComputeInstanceClassesGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComputeInstanceClasses_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ComputeInstanceClassesCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputeInstanceClassesServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComputeInstanceClasses_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputeInstanceClassesServer).Create(ctx, req.(*ComputeInstanceClassesCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComputeInstanceClasses_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ComputeInstanceClassesUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputeInstanceClassesServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComputeInstanceClasses_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputeInstanceClassesServer).Update(ctx, req.(*ComputeInstanceClassesUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComputeInstanceClasses_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ComputeInstanceClassesDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputeInstanceClassesServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComputeInstanceClasses_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputeInstanceClassesServer).Delete(ctx, req.(*ComputeInstanceClassesDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComputeInstanceClasses_Signal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ComputeInstanceClassesSignalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputeInstanceClassesServer).Signal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComputeInstanceClasses_Signal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputeInstanceClassesServer).Signal(ctx, req.(*ComputeInstanceClassesSignalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ComputeInstanceClasses_ServiceDesc is the grpc.ServiceDesc for ComputeInstanceClasses service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ComputeInstanceClasses_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "osac.private.v1.ComputeInstanceClasses",
	HandlerType: (*ComputeInstanceClassesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _ComputeInstanceClasses_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _ComputeInstanceClasses_Get_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _ComputeInstanceClasses_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ComputeInstanceClasses_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ComputeInstanceClasses_Delete_Handler,
		},
		{
			MethodName: "Signal",
			Handler:    _ComputeInstanceClasses_Signal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "osac/private/v1/compute_instance_classes_service.proto",
}
