//
// Copyright (c) 2025 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: osac/private/v1/provisioning_metadata_type.proto

//go:build !protoopaque

package privatev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Binds a catalog item to an Ansible collection and ResourceAction for provisioning dispatch.
// The operator reads this metadata to determine which AAP Job Template to invoke.
type ProvisioningMetadata struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Ansible collection that contains the provisioning roles (e.g., "osac.compute_kubevirt", "netris.osac").
	// This is the Galaxy-compatible namespace.collection identifier.
	Collection string `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	// Resource action prefix within the collection (e.g., "instance", "cluster", "virtual_network").
	// The operator derives the full role name by appending the event and phase:
	// <resource_action>.<event>.main (e.g., "instance.create.main").
	ResourceAction string `protobuf:"bytes,2,opt,name=resource_action,json=resourceAction,proto3" json:"resource_action,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProvisioningMetadata) Reset() {
	*x = ProvisioningMetadata{}
	mi := &file_osac_private_v1_provisioning_metadata_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisioningMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisioningMetadata) ProtoMessage() {}

func (x *ProvisioningMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_provisioning_metadata_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ProvisioningMetadata) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *ProvisioningMetadata) GetResourceAction() string {
	if x != nil {
		return x.ResourceAction
	}
	return ""
}

func (x *ProvisioningMetadata) SetCollection(v string) {
	x.Collection = v
}

func (x *ProvisioningMetadata) SetResourceAction(v string) {
	x.ResourceAction = v
}

type ProvisioningMetadata_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Ansible collection that contains the provisioning roles (e.g., "osac.compute_kubevirt", "netris.osac").
	// This is the Galaxy-compatible namespace.collection identifier.
	Collection string
	// Resource action prefix within the collection (e.g., "instance", "cluster", "virtual_network").
	// The operator derives the full role name by appending the event and phase:
	// <resource_action>.<event>.main (e.g., "instance.create.main").
	ResourceAction string
}

func (b0 ProvisioningMetadata_builder) Build() *ProvisioningMetadata {
	m0 := &ProvisioningMetadata{}
	b, x := &b0, m0
	_, _ = b, x
	x.Collection = b.Collection
	x.ResourceAction = b.ResourceAction
	return m0
}

var File_osac_private_v1_provisioning_metadata_type_proto protoreflect.FileDescriptor

var file_osac_private_v1_provisioning_metadata_type_proto_rawDesc = string([]byte{
	0x0a, 0x30, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x76,
	0x31, 0x2f, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x69, 0x6e, 0x67, 0x5f, 0x6d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0f, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x2e, 0x76, 0x31, 0x22, 0x5f, 0x0a, 0x14, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e,
	0x69, 0x6e, 0x67, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1e, 0x0a, 0x0a, 0x63,
	0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x27, 0x0a, 0x0f, 0x72,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x41, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x42, 0xe8, 0x01, 0x0a, 0x13, 0x63, 0x6f, 0x6d, 0x2e, 0x6f, 0x73, 0x61,
	0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x42, 0x1d, 0x50, 0x72,
	0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x69, 0x6e, 0x67, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x52, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x73, 0x61, 0x63, 0x2d, 0x70,
	0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2f, 0x66, 0x75, 0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x6d, 0x65,
	0x6e, 0x74, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x72, 0x69,
	0x76, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x76,
	0x31, 0xa2, 0x02, 0x03, 0x4f, 0x50, 0x58, 0xaa, 0x02, 0x0f, 0x4f, 0x73, 0x61, 0x63, 0x2e, 0x50,
	0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x10, 0x4f, 0x73, 0x61, 0x63,
	0x5c, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x1c, 0x4f,
	0x73, 0x61, 0x63, 0x5c, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x5c, 0x56, 0x31, 0x5c,
	0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x11, 0x4f, 0x73,
	0x61, 0x63, 0x3a, 0x3a, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x3a, 0x3a, 0x56, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var file_osac_private_v1_provisioning_metadata_type_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_osac_private_v1_provisioning_metadata_type_proto_goTypes = []any{
	(*ProvisioningMetadata)(nil), // 0: osac.private.v1.ProvisioningMetadata
}
var file_osac_private_v1_provisioning_metadata_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_osac_private_v1_provisioning_metadata_type_proto_init() }
func file_osac_private_v1_provisioning_metadata_type_proto_init() {
	if File_osac_private_v1_provisioning_metadata_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_osac_private_v1_provisioning_metadata_type_proto_rawDesc), len(file_osac_private_v1_provisioning_metadata_type_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_osac_private_v1_provisioning_metadata_type_proto_goTypes,
		DependencyIndexes: file_osac_private_v1_provisioning_metadata_type_proto_depIdxs,
		MessageInfos:      file_osac_private_v1_provisioning_metadata_type_proto_msgTypes,
	}.Build()
	File_osac_private_v1_provisioning_metadata_type_proto = out.File
	file_osac_private_v1_provisioning_metadata_type_proto_goTypes = nil
	file_osac_private_v1_provisioning_metadata_type_proto_depIdxs = nil
}
