//
// Copyright (c) 2025 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: osac/private/v1/ssh_keys_service.proto

//go:build !protoopaque

package privatev1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SSHKeysListRequest struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Index of the first result. If not specified the default value will be zero.
	Offset *int32 `protobuf:"varint,1,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	// Maximum number of results to be returned by the server. When not specified all the results will be returned. Note
	// that there may not be enough results to return, and that the server may decide, for performance reasons, to return
	// less results than requested.
	Limit *int32 `protobuf:"varint,2,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	// Filter criteria.
	//
	// The value of this parameter is a [CEL](https://cel.dev) expression used to select which objects to return. The
	// built-in `this` variable refers to the object being tested and `now` refers to the current date and time. If the
	// expression evaluates to `true` the object is included in the results. For example, to retrieve all SSH keys
	// with names starting with `prod`:
	//
	//	this.metadata.name.startsWith("prod")
	//
	// If this isn't provided, or if the value is empty, then all the SSH keys that the user has permission to see
	// will be returned. Not all CEL constructs are currently supported for implementation reasons; see the filter
	// documentation (docs/FILTER.md) for the full details.
	Filter *string `protobuf:"bytes,3,opt,name=filter,proto3,oneof" json:"filter,omitempty"`
	// Order criteria.
	//
	// The syntax of this parameter is similar to the syntax of the _order by_ clause of a SQL statement, but using the
	// names of the attributes of the SSH key instead of the names of the columns of a table. For example, in order to
	// sort the SSH keys descending by name the value should be:
	//
	//	metadata.name desc
	//
	// If the parameter isn't provided, or if the value is empty, then the order of the results is undefined.
	Order         *string `protobuf:"bytes,4,opt,name=order,proto3,oneof" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SSHKeysListRequest) Reset() {
	*x = SSHKeysListRequest{}
	mi := &file_osac_private_v1_ssh_keys_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SSHKeysListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSHKeysListRequest) ProtoMessage() {}

func (x *SSHKeysListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_ssh_keys_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SSHKeysListRequest) GetOffset() int32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *SSHKeysListRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *SSHKeysListRequest) GetFilter() string {
	if x != nil && x.Filter != nil {
		return *x.Filter
	}
	return ""
}

func (x *SSHKeysListRequest) GetOrder() string {
	if x != nil && x.Order != nil {
		return *x.Order
	}
	return ""
}

func (x *SSHKeysListRequest) SetOffset(v int32) {
	x.Offset = &v
}

func (x *SSHKeysListRequest) SetLimit(v int32) {
	x.Limit = &v
}

func (x *SSHKeysListRequest) SetFilter(v string) {
	x.Filter = &v
}

func (x *SSHKeysListRequest) SetOrder(v string) {
	x.Order = &v
}

func (x *SSHKeysListRequest) HasOffset() bool {
	if x == nil {
		return false
	}
	return x.Offset != nil
}

func (x *SSHKeysListRequest) HasLimit() bool {
	if x == nil {
		return false
	}
	return x.Limit != nil
}

func (x *SSHKeysListRequest) HasFilter() bool {
	if x == nil {
		return false
	}
	return x.Filter != nil
}

func (x *SSHKeysListRequest) HasOrder() bool {
	if x == nil {
		return false
	}
	return x.Order != nil
}

func (x *SSHKeysListRequest) ClearOffset() {
	x.Offset = nil
}

func (x *SSHKeysListRequest) ClearLimit() {
	x.Limit = nil
}

func (x *SSHKeysListRequest) ClearFilter() {
	x.Filter = nil
}

func (x *SSHKeysListRequest) ClearOrder() {
	x.Order = nil
}

type SSHKeysListRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Index of the first result. If not specified the default value will be zero.
	Offset *int32
	// Maximum number of results to be returned by the server. When not specified all the results will be returned. Note
	// that there may not be enough results to return, and that the server may decide, for performance reasons, to return
	// less results than requested.
	Limit *int32
	// Filter criteria.
	//
	// The value of this parameter is a [CEL](https://cel.dev) expression used to select which objects to return. The
	// built-in `this` variable refers to the object being tested and `now` refers to the current date and time. If the
	// expression evaluates to `true` the object is included in the results. For example, to retrieve all SSH keys
	// with names starting with `prod`:
	//
	//	this.metadata.name.startsWith("prod")
	//
	// If this isn't provided, or if the value is empty, then all the SSH keys that the user has permission to see
	// will be returned. Not all CEL constructs are currently supported for implementation reasons; see the filter
	// documentation (docs/FILTER.md) for the full details.
	Filter *string
	// Order criteria.
	//
	// The syntax of this parameter is similar to the syntax of the _order by_ clause of a SQL statement, but using the
	// names of the attributes of the SSH key instead of the names of the columns of a table. For example, in order to
	// sort the SSH keys descending by name the value should be:
	//
	//	metadata.name desc
	//
	// If the parameter isn't provided, or if the value is empty, then the order of the results is undefined.
	Order *string
}

func (b0 SSHKeysListRequest_builder) Build() *SSHKeysListRequest {
	m0 := &SSHKeysListRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.Offset = b.Offset
	x.Limit = b.Limit
	x.Filter = b.Filter
	x.Order = b.Order
	return m0
}

type SSHKeysListResponse struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Actual number of items returned. Note that this may be smaller than the value requested in the `limit` parameter
	// of the request if there are not enough items, or if the system decides that returning that number of items isn't
	// feasible or convenient for performance reasons.
	Size int32 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	// Total number of items of the collection that match the search criteria, regardless of the number of results
	// requested with the `limit` parameter.
	Total int32 `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	// List of results.
	Items         []*SSHKey `protobuf:"bytes,5,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SSHKeysListResponse) Reset() {
	*x = SSHKeysListResponse{}
	mi := &file_osac_private_v1_ssh_keys_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SSHKeysListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSHKeysListResponse) ProtoMessage() {}

func (x *SSHKeysListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_ssh_keys_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SSHKeysListResponse) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *SSHKeysListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SSHKeysListResponse) GetItems() []*SSHKey {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *SSHKeysListResponse) SetSize(v int32) {
	x.Size = v
}

func (x *SSHKeysListResponse) SetTotal(v int32) {
	x.Total = v
}

func (x *SSHKeysListResponse) SetItems(v []*SSHKey) {
	x.Items = v
}

type SSHKeysListResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Actual number of items returned. Note that this may be smaller than the value requested in the `limit` parameter
	// of the request if there are not enough items, or if the system decides that returning that number of items isn't
	// feasible or convenient for performance reasons.
	Size int32
	// Total number of items of the collection that match the search criteria, regardless of the number of results
	// requested with the `limit` parameter.
	Total int32
	// List of results.
	Items []*SSHKey
}

func (b0 SSHKeysListResponse_builder) Build() *SSHKeysListResponse {
	m0 := &SSHKeysListResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.Size = b.Size
	x.Total = b.Total
	x.Items = b.Items
	return m0
}

type SSHKeysGetRequest struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SSHKeysGetRequest) Reset() {
	*x = SSHKeysGetRequest{}
	mi := &file_osac_private_v1_ssh_keys_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SSHKeysGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSHKeysGetRequest) ProtoMessage() {}

func (x *SSHKeysGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_ssh_keys_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SSHKeysGetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SSHKeysGetRequest) SetId(v string) {
	x.Id = v
}

type SSHKeysGetRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id string
}

func (b0 SSHKeysGetRequest_builder) Build() *SSHKeysGetRequest {
	m0 := &SSHKeysGetRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.Id = b.Id
	return m0
}

type SSHKeysGetResponse struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Object        *SSHKey                `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SSHKeysGetResponse) Reset() {
	*x = SSHKeysGetResponse{}
	mi := &file_osac_private_v1_ssh_keys_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SSHKeysGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSHKeysGetResponse) ProtoMessage() {}

func (x *SSHKeysGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_ssh_keys_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SSHKeysGetResponse) GetObject() *SSHKey {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *SSHKeysGetResponse) SetObject(v *SSHKey) {
	x.Object = v
}

func (x *SSHKeysGetResponse) HasObject() bool {
	if x == nil {
		return false
	}
	return x.Object != nil
}

func (x *SSHKeysGetResponse) ClearObject() {
	x.Object = nil
}

type SSHKeysGetResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Object *SSHKey
}

func (b0 SSHKeysGetResponse_builder) Build() *SSHKeysGetResponse {
	m0 := &SSHKeysGetResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.Object = b.Object
	return m0
}

type SSHKeysCreateRequest struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Object        *SSHKey                `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SSHKeysCreateRequest) Reset() {
	*x = SSHKeysCreateRequest{}
	mi := &file_osac_private_v1_ssh_keys_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SSHKeysCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSHKeysCreateRequest) ProtoMessage() {}

func (x *SSHKeysCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_ssh_keys_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SSHKeysCreateRequest) GetObject() *SSHKey {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *SSHKeysCreateRequest) SetObject(v *SSHKey) {
	x.Object = v
}

func (x *SSHKeysCreateRequest) HasObject() bool {
	if x == nil {
		return false
	}
	return x.Object != nil
}

func (x *SSHKeysCreateRequest) ClearObject() {
	x.Object = nil
}

type SSHKeysCreateRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Object *SSHKey
}

func (b0 SSHKeysCreateRequest_builder) Build() *SSHKeysCreateRequest {
	m0 := &SSHKeysCreateRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.Object = b.Object
	return m0
}

type SSHKeysCreateResponse struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Object        *SSHKey                `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SSHKeysCreateResponse) Reset() {
	*x = SSHKeysCreateResponse{}
	mi := &file_osac_private_v1_ssh_keys_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SSHKeysCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSHKeysCreateResponse) ProtoMessage() {}

func (x *SSHKeysCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_ssh_keys_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SSHKeysCreateResponse) GetObject() *SSHKey {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *SSHKeysCreateResponse) SetObject(v *SSHKey) {
	x.Object = v
}

func (x *SSHKeysCreateResponse) HasObject() bool {
	if x == nil {
		return false
	}
	return x.Object != nil
}

func (x *SSHKeysCreateResponse) ClearObject() {
	x.Object = nil
}

type SSHKeysCreateResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Object *SSHKey
}

func (b0 SSHKeysCreateResponse_builder) Build() *SSHKeysCreateResponse {
	m0 := &SSHKeysCreateResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.Object = b.Object
	return m0
}

type SSHKeysUpdateRequest struct {
	state      protoimpl.MessageState `protogen:"hybrid.v1"`
	Object     *SSHKey                `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	UpdateMask *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	// Lock enables optimistic locking. When set to true, the server verifies that the current version of the object
	// matches the value of the metadata.version field of the submitted object. If they differ the update will be
	// rejected. This is useful to prevent lost updates when multiple clients are modifying the same object concurrently.
	Lock          bool `protobuf:"varint,3,opt,name=lock,proto3" json:"lock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SSHKeysUpdateRequest) Reset() {
	*x = SSHKeysUpdateRequest{}
	mi := &file_osac_private_v1_ssh_keys_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SSHKeysUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSHKeysUpdateRequest) ProtoMessage() {}

func (x *SSHKeysUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_ssh_keys_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SSHKeysUpdateRequest) GetObject() *SSHKey {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *SSHKeysUpdateRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

func (x *SSHKeysUpdateRequest) GetLock() bool {
	if x != nil {
		return x.Lock
	}
	return false
}

func (x *SSHKeysUpdateRequest) SetObject(v *SSHKey) {
	x.Object = v
}

func (x *SSHKeysUpdateRequest) SetUpdateMask(v *fieldmaskpb.FieldMask) {
	x.UpdateMask = v
}

func (x *SSHKeysUpdateRequest) SetLock(v bool) {
	x.Lock = v
}

func (x *SSHKeysUpdateRequest) HasObject() bool {
	if x == nil {
		return false
	}
	return x.Object != nil
}

func (x *SSHKeysUpdateRequest) HasUpdateMask() bool {
	if x == nil {
		return false
	}
	return x.UpdateMask != nil
}

func (x *SSHKeysUpdateRequest) ClearObject() {
	x.Object = nil
}

func (x *SSHKeysUpdateRequest) ClearUpdateMask() {
	x.UpdateMask = nil
}

type SSHKeysUpdateRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Object     *SSHKey
	UpdateMask *fieldmaskpb.FieldMask
	// Lock enables optimistic locking. When set to true, the server verifies that the current version of the object
	// matches the value of the metadata.version field of the submitted object. If they differ the update will be
	// rejected. This is useful to prevent lost updates when multiple clients are modifying the same object concurrently.
	Lock bool
}

func (b0 SSHKeysUpdateRequest_builder) Build() *SSHKeysUpdateRequest {
	m0 := &SSHKeysUpdateRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.Object = b.Object
	x.UpdateMask = b.UpdateMask
	x.Lock = b.Lock
	return m0
}

type SSHKeysUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Object        *SSHKey                `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SSHKeysUpdateResponse) Reset() {
	*x = SSHKeysUpdateResponse{}
	mi := &file_osac_private_v1_ssh_keys_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SSHKeysUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSHKeysUpdateResponse) ProtoMessage() {}

func (x *SSHKeysUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_ssh_keys_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SSHKeysUpdateResponse) GetObject() *SSHKey {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *SSHKeysUpdateResponse) SetObject(v *SSHKey) {
	x.Object = v
}

func (x *SSHKeysUpdateResponse) HasObject() bool {
	if x == nil {
		return false
	}
	return x.Object != nil
}

func (x *SSHKeysUpdateResponse) ClearObject() {
	x.Object = nil
}

type SSHKeysUpdateResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Object *SSHKey
}

func (b0 SSHKeysUpdateResponse_builder) Build() *SSHKeysUpdateResponse {
	m0 := &SSHKeysUpdateResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.Object = b.Object
	return m0
}

type SSHKeysDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SSHKeysDeleteRequest) Reset() {
	*x = SSHKeysDeleteRequest{}
	mi := &file_osac_private_v1_ssh_keys_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SSHKeysDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSHKeysDeleteRequest) ProtoMessage() {}

func (x *SSHKeysDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_ssh_keys_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SSHKeysDeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SSHKeysDeleteRequest) SetId(v string) {
	x.Id = v
}

type SSHKeysDeleteRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id string
}

func (b0 SSHKeysDeleteRequest_builder) Build() *SSHKeysDeleteRequest {
	m0 := &SSHKeysDeleteRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.Id = b.Id
	return m0
}

type SSHKeysDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SSHKeysDeleteResponse) Reset() {
	*x = SSHKeysDeleteResponse{}
	mi := &file_osac_private_v1_ssh_keys_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SSHKeysDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSHKeysDeleteResponse) ProtoMessage() {}

func (x *SSHKeysDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_ssh_keys_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type SSHKeysDeleteResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 SSHKeysDeleteResponse_builder) Build() *SSHKeysDeleteResponse {
	m0 := &SSHKeysDeleteResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type SSHKeysSignalRequest struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SSHKeysSignalRequest) Reset() {
	*x = SSHKeysSignalRequest{}
	mi := &file_osac_private_v1_ssh_keys_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SSHKeysSignalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSHKeysSignalRequest) ProtoMessage() {}

func (x *SSHKeysSignalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_ssh_keys_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SSHKeysSignalRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SSHKeysSignalRequest) SetId(v string) {
	x.Id = v
}

type SSHKeysSignalRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id string
}

func (b0 SSHKeysSignalRequest_builder) Build() *SSHKeysSignalRequest {
	m0 := &SSHKeysSignalRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.Id = b.Id
	return m0
}

type SSHKeysSignalResponse struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SSHKeysSignalResponse) Reset() {
	*x = SSHKeysSignalResponse{}
	mi := &file_osac_private_v1_ssh_keys_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SSHKeysSignalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSHKeysSignalResponse) ProtoMessage() {}

func (x *SSHKeysSignalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_osac_private_v1_ssh_keys_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type SSHKeysSignalResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 SSHKeysSignalResponse_builder) Build() *SSHKeysSignalResponse {
	m0 := &SSHKeysSignalResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_osac_private_v1_ssh_keys_service_proto protoreflect.FileDescriptor

var file_osac_private_v1_ssh_keys_service_proto_rawDesc = string([]byte{
	0x0a, 0x26, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x76,
	0x31, 0x2f, 0x73, 0x73, 0x68, 0x5f, 0x6b, 0x65, 0x79, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70,
	0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x6d,
	0x61, 0x73, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x22, 0x6f, 0x73, 0x61, 0x63, 0x2f,
	0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x73, 0x68, 0x5f, 0x6b,
	0x65, 0x79, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xae, 0x01,
	0x0a, 0x12, 0x53, 0x53, 0x48, 0x4b, 0x65, 0x79, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x88, 0x01,
	0x01, 0x12, 0x19, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x48, 0x01, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x88, 0x01, 0x01, 0x12, 0x1b, 0x0a, 0x06,
	0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x06,
	0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x88, 0x01, 0x01, 0x12, 0x19, 0x0a, 0x05, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x03, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x88, 0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x42,
	0x08, 0x0a, 0x06, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x66, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x22, 0x6e,
	0x0a, 0x13, 0x53, 0x53, 0x48, 0x4b, 0x65, 0x79, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12,
	0x2d, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x53, 0x53, 0x48, 0x4b, 0x65, 0x79, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x23,
	0x0a, 0x11, 0x53, 0x53, 0x48, 0x4b, 0x65, 0x79, 0x73, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x45, 0x0a, 0x12, 0x53, 0x53, 0x48, 0x4b, 0x65, 0x79, 0x73, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x06, 0x6f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6f, 0x73, 0x61, 0x63,
	0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x53, 0x48, 0x4b,
	0x65, 0x79, 0x52, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x22, 0x47, 0x0a, 0x14, 0x53, 0x53,
	0x48, 0x4b, 0x65, 0x79, 0x73, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x2f, 0x0a, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x53, 0x48, 0x4b, 0x65, 0x79, 0x52, 0x06, 0x6f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x22, 0x48, 0x0a, 0x15, 0x53, 0x53, 0x48, 0x4b, 0x65, 0x79, 0x73, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x06,
	0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6f,
	0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53,
	0x53, 0x48, 0x4b, 0x65, 0x79, 0x52, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x22, 0x98, 0x01,
	0x0a, 0x14, 0x53, 0x53, 0x48, 0x4b, 0x65, 0x79, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2f, 0x0a, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72,
	0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x53, 0x48, 0x4b, 0x65, 0x79, 0x52,
	0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x3b, 0x0a, 0x0b, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x5f, 0x6d, 0x61, 0x73, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46,
	0x69, 0x65, 0x6c, 0x64, 0x4d, 0x61, 0x73, 0x6b, 0x52, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x4d, 0x61, 0x73, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x04, 0x6c, 0x6f, 0x63, 0x6b, 0x22, 0x48, 0x0a, 0x15, 0x53, 0x53, 0x48, 0x4b,
	0x65, 0x79, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2f, 0x0a, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x53, 0x53, 0x48, 0x4b, 0x65, 0x79, 0x52, 0x06, 0x6f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x22, 0x26, 0x0a, 0x14, 0x53, 0x53, 0x48, 0x4b, 0x65, 0x79, 0x73, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x17, 0x0a, 0x15, 0x53, 0x53,
	0x48, 0x4b, 0x65, 0x79, 0x73, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x26, 0x0a, 0x14, 0x53, 0x53, 0x48, 0x4b, 0x65, 0x79, 0x73, 0x53, 0x69,
	0x67, 0x6e, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x17, 0x0a, 0x15, 0x53,
	0x53, 0x48, 0x4b, 0x65, 0x79, 0x73, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x32, 0xfc, 0x05, 0x0a, 0x07, 0x53, 0x53, 0x48, 0x4b, 0x65, 0x79, 0x73,
	0x12, 0x73, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x23, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e,
	0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x53, 0x48, 0x4b, 0x65,
	0x79, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e,
	0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x53, 0x53, 0x48, 0x4b, 0x65, 0x79, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x20, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1a, 0x12, 0x18, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x73, 0x68,
	0x5f, 0x6b, 0x65, 0x79, 0x73, 0x12, 0x7d, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x22, 0x2e, 0x6f,
	0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53,
	0x53, 0x48, 0x4b, 0x65, 0x79, 0x73, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x23, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x53, 0x53, 0x48, 0x4b, 0x65, 0x79, 0x73, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2d, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x27, 0x62, 0x06, 0x6f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x1d, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x69, 0x76,
	0x61, 0x74, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x73, 0x68, 0x5f, 0x6b, 0x65, 0x79, 0x73, 0x2f,
	0x7b, 0x69, 0x64, 0x7d, 0x12, 0x89, 0x01, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12,
	0x25, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x53, 0x53, 0x48, 0x4b, 0x65, 0x79, 0x73, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72,
	0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x53, 0x48, 0x4b, 0x65, 0x79, 0x73,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x30,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x2a, 0x3a, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x62, 0x06,
	0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x22, 0x18, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x69,
	0x76, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x73, 0x68, 0x5f, 0x6b, 0x65, 0x79, 0x73,
	0x12, 0x95, 0x01, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x25, 0x2e, 0x6f, 0x73,
	0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x53,
	0x48, 0x4b, 0x65, 0x79, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x26, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x53, 0x48, 0x4b, 0x65, 0x79, 0x73, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x3c, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x36, 0x3a, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x62, 0x06, 0x6f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x32, 0x24, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x2f, 0x76, 0x31, 0x2f, 0x73, 0x73, 0x68, 0x5f, 0x6b, 0x65, 0x79, 0x73, 0x2f, 0x7b, 0x6f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x2e, 0x69, 0x64, 0x7d, 0x12, 0x7e, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x12, 0x25, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x53, 0x48, 0x4b, 0x65, 0x79, 0x73, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x6f, 0x73, 0x61, 0x63,
	0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x53, 0x48, 0x4b,
	0x65, 0x79, 0x73, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x25, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1f, 0x2a, 0x1d, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x73, 0x68, 0x5f, 0x6b,
	0x65, 0x79, 0x73, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x12, 0x59, 0x0a, 0x06, 0x53, 0x69, 0x67, 0x6e,
	0x61, 0x6c, 0x12, 0x25, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x53, 0x48, 0x4b, 0x65, 0x79, 0x73, 0x53, 0x69, 0x67, 0x6e,
	0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x6f, 0x73, 0x61, 0x63,
	0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x53, 0x48, 0x4b,
	0x65, 0x79, 0x73, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0xde, 0x01, 0x0a, 0x13, 0x63, 0x6f, 0x6d, 0x2e, 0x6f, 0x73, 0x61, 0x63,
	0x2e, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31, 0x42, 0x13, 0x53, 0x73, 0x68,
	0x4b, 0x65, 0x79, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x50, 0x01, 0x5a, 0x52, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f,
	0x73, 0x61, 0x63, 0x2d, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2f, 0x66, 0x75, 0x6c, 0x66,
	0x69, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x73, 0x61,
	0x63, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x70, 0x72, 0x69,
	0x76, 0x61, 0x74, 0x65, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x4f, 0x50, 0x58, 0xaa, 0x02, 0x0f, 0x4f,
	0x73, 0x61, 0x63, 0x2e, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x56, 0x31, 0xca, 0x02,
	0x10, 0x4f, 0x73, 0x61, 0x63, 0x5c, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x5c, 0x56,
	0x31, 0xe2, 0x02, 0x1c, 0x4f, 0x73, 0x61, 0x63, 0x5c, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x5f, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0xea, 0x02, 0x11, 0x4f, 0x73, 0x61, 0x63, 0x3a, 0x3a, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var file_osac_private_v1_ssh_keys_service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_osac_private_v1_ssh_keys_service_proto_goTypes = []any{
	(*SSHKeysListRequest)(nil),    // 0: osac.private.v1.SSHKeysListRequest
	(*SSHKeysListResponse)(nil),   // 1: osac.private.v1.SSHKeysListResponse
	(*SSHKeysGetRequest)(nil),     // 2: osac.private.v1.SSHKeysGetRequest
	(*SSHKeysGetResponse)(nil),    // 3: osac.private.v1.SSHKeysGetResponse
	(*SSHKeysCreateRequest)(nil),  // 4: osac.private.v1.SSHKeysCreateRequest
	(*SSHKeysCreateResponse)(nil), // 5: osac.private.v1.SSHKeysCreateResponse
	(*SSHKeysUpdateRequest)(nil),  // 6: osac.private.v1.SSHKeysUpdateRequest
	(*SSHKeysUpdateResponse)(nil), // 7: osac.private.v1.SSHKeysUpdateResponse
	(*SSHKeysDeleteRequest)(nil),  // 8: osac.private.v1.SSHKeysDeleteRequest
	(*SSHKeysDeleteResponse)(nil), // 9: osac.private.v1.SSHKeysDeleteResponse
	(*SSHKeysSignalRequest)(nil),  // 10: osac.private.v1.SSHKeysSignalRequest
	(*SSHKeysSignalResponse)(nil), // 11: osac.private.v1.SSHKeysSignalResponse
	(*SSHKey)(nil),                // 12: osac.private.v1.SSHKey
	(*fieldmaskpb.FieldMask)(nil), // 13: google.protobuf.FieldMask
}
var file_osac_private_v1_ssh_keys_service_proto_depIdxs = []int32{
	12, // 0: osac.private.v1.SSHKeysListResponse.items:type_name -> osac.private.v1.SSHKey
	12, // 1: osac.private.v1.SSHKeysGetResponse.object:type_name -> osac.private.v1.SSHKey
	12, // 2: osac.private.v1.SSHKeysCreateRequest.object:type_name -> osac.private.v1.SSHKey
	12, // 3: osac.private.v1.SSHKeysCreateResponse.object:type_name -> osac.private.v1.SSHKey
	12, // 4: osac.private.v1.SSHKeysUpdateRequest.object:type_name -> osac.private.v1.SSHKey
	13, // 5: osac.private.v1.SSHKeysUpdateRequest.update_mask:type_name -> google.protobuf.FieldMask
	12, // 6: osac.private.v1.SSHKeysUpdateResponse.object:type_name -> osac.private.v1.SSHKey
	0,  // 7: osac.private.v1.SSHKeys.List:input_type -> osac.private.v1.SSHKeysListRequest
	2,  // 8: osac.private.v1.SSHKeys.Get:input_type -> osac.private.v1.SSHKeysGetRequest
	4,  // 9: osac.private.v1.SSHKeys.Create:input_type -> osac.private.v1.SSHKeysCreateRequest
	6,  // 10: osac.private.v1.SSHKeys.Update:input_type -> osac.private.v1.SSHKeysUpdateRequest
	8,  // 11: osac.private.v1.SSHKeys.Delete:input_type -> osac.private.v1.SSHKeysDeleteRequest
	10, // 12: osac.private.v1.SSHKeys.Signal:input_type -> osac.private.v1.SSHKeysSignalRequest
	1,  // 13: osac.private.v1.SSHKeys.List:output_type -> osac.private.v1.SSHKeysListResponse
	3,  // 14: osac.private.v1.SSHKeys.Get:output_type -> osac.private.v1.SSHKeysGetResponse
	5,  // 15: osac.private.v1.SSHKeys.Create:output_type -> osac.private.v1.SSHKeysCreateResponse
	7,  // 16: osac.private.v1.SSHKeys.Update:output_type -> osac.private.v1.SSHKeysUpdateResponse
	9,  // 17: osac.private.v1.SSHKeys.Delete:output_type -> osac.private.v1.SSHKeysDeleteResponse
	11, // 18: osac.private.v1.SSHKeys.Signal:output_type -> osac.private.v1.SSHKeysSignalResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_osac_private_v1_ssh_keys_service_proto_init() }
func file_osac_private_v1_ssh_keys_service_proto_init() {
	if File_osac_private_v1_ssh_keys_service_proto != nil {
		return
	}
	file_osac_private_v1_ssh_key_type_proto_init()
	file_osac_private_v1_ssh_keys_service_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_osac_private_v1_ssh_keys_service_proto_rawDesc), len(file_osac_private_v1_ssh_keys_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_osac_private_v1_ssh_keys_service_proto_goTypes,
		DependencyIndexes: file_osac_private_v1_ssh_keys_service_proto_depIdxs,
		MessageInfos:      file_osac_private_v1_ssh_keys_service_proto_msgTypes,
	}.Build()
	File_osac_private_v1_ssh_keys_service_proto = out.File
	file_osac_private_v1_ssh_keys_service_proto_goTypes = nil
	file_osac_private_v1_ssh_keys_service_proto_depIdxs = nil
}
