//
// Copyright (c) 2026 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: osac/private/v1/ssh_keys_service.proto

package privatev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SSHKeys_List_FullMethodName   = "/osac.private.v1.SSHKeys/List"
	SSHKeys_Get_FullMethodName    = "/osac.private.v1.SSHKeys/Get"
	SSHKeys_Create_FullMethodName = "/osac.private.v1.SSHKeys/Create"
	SSHKeys_Update_FullMethodName = "/osac.private.v1.SSHKeys/Update"
	SSHKeys_Delete_FullMethodName = "/osac.private.v1.SSHKeys/Delete"
	SSHKeys_Signal_FullMethodName = "/osac.private.v1.SSHKeys/Signal"
)

// SSHKeysClient is the client API for SSHKeys service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SSHKeysClient interface {
	// Retrieves the list of SSH keys.
	List(ctx context.Context, in *SSHKeysListRequest, opts ...grpc.CallOption) (*SSHKeysListResponse, error)
	// Retrieves the details of one specific SSH key.
	Get(ctx context.Context, in *SSHKeysGetRequest, opts ...grpc.CallOption) (*SSHKeysGetResponse, error)
	// Creates a new SSH key.
	Create(ctx context.Context, in *SSHKeysCreateRequest, opts ...grpc.CallOption) (*SSHKeysCreateResponse, error)
	// Updates an existing SSH key.
	Update(ctx context.Context, in *SSHKeysUpdateRequest, opts ...grpc.CallOption) (*SSHKeysUpdateResponse, error)
	// Deletes an SSH key.
	Delete(ctx context.Context, in *SSHKeysDeleteRequest, opts ...grpc.CallOption) (*SSHKeysDeleteResponse, error)
	// Indicates that something changed in the object or the system that may require reconciling the object.
	Signal(ctx context.Context, in *SSHKeysSignalRequest, opts ...grpc.CallOption) (*SSHKeysSignalResponse, error)
}

type sSHKeysClient struct {
	cc grpc.ClientConnInterface
}

func NewSSHKeysClient(cc grpc.ClientConnInterface) SSHKeysClient {
	return &sSHKeysClient{cc}
}

func (c *sSHKeysClient) List(ctx context.Context, in *SSHKeysListRequest, opts ...grpc.CallOption) (*SSHKeysListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SSHKeysListResponse)
	err := c.cc.Invoke(ctx, SSHKeys_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sSHKeysClient) Get(ctx context.Context, in *SSHKeysGetRequest, opts ...grpc.CallOption) (*SSHKeysGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SSHKeysGetResponse)
	err := c.cc.Invoke(ctx, SSHKeys_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sSHKeysClient) Create(ctx context.Context, in *SSHKeysCreateRequest, opts ...grpc.CallOption) (*SSHKeysCreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SSHKeysCreateResponse)
	err := c.cc.Invoke(ctx, SSHKeys_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sSHKeysClient) Update(ctx context.Context, in *SSHKeysUpdateRequest, opts ...grpc.CallOption) (*SSHKeysUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SSHKeysUpdateResponse)
	err := c.cc.Invoke(ctx, SSHKeys_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sSHKeysClient) Delete(ctx context.Context, in *SSHKeysDeleteRequest, opts ...grpc.CallOption) (*SSHKeysDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SSHKeysDeleteResponse)
	err := c.cc.Invoke(ctx, SSHKeys_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sSHKeysClient) Signal(ctx context.Context, in *SSHKeysSignalRequest, opts ...grpc.CallOption) (*SSHKeysSignalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SSHKeysSignalResponse)
	err := c.cc.Invoke(ctx, SSHKeys_Signal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SSHKeysServer is the server API for SSHKeys service.
// All implementations must embed UnimplementedSSHKeysServer
// for forward compatibility.
type SSHKeysServer interface {
	// Retrieves the list of SSH keys.
	List(context.Context, *SSHKeysListRequest) (*SSHKeysListResponse, error)
	// Retrieves the details of one specific SSH key.
	Get(context.Context, *SSHKeysGetRequest) (*SSHKeysGetResponse, error)
	// Creates a new SSH key.
	Create(context.Context, *SSHKeysCreateRequest) (*SSHKeysCreateResponse, error)
	// Updates an existing SSH key.
	Update(context.Context, *SSHKeysUpdateRequest) (*SSHKeysUpdateResponse, error)
	// Deletes an SSH key.
	Delete(context.Context, *SSHKeysDeleteRequest) (*SSHKeysDeleteResponse, error)
	// Indicates that something changed in the object or the system that may require reconciling the object.
	Signal(context.Context, *SSHKeysSignalRequest) (*SSHKeysSignalResponse, error)
	mustEmbedUnimplementedSSHKeysServer()
}

// UnimplementedSSHKeysServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSSHKeysServer struct{}

func (UnimplementedSSHKeysServer) List(context.Context, *SSHKeysListRequest) (*SSHKeysListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedSSHKeysServer) Get(context.Context, *SSHKeysGetRequest) (*SSHKeysGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedSSHKeysServer) Create(context.Context, *SSHKeysCreateRequest) (*SSHKeysCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedSSHKeysServer) Update(context.Context, *SSHKeysUpdateRequest) (*SSHKeysUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedSSHKeysServer) Delete(context.Context, *SSHKeysDeleteRequest) (*SSHKeysDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedSSHKeysServer) Signal(context.Context, *SSHKeysSignalRequest) (*SSHKeysSignalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Signal not implemented")
}
func (UnimplementedSSHKeysServer) mustEmbedUnimplementedSSHKeysServer() {}
func (UnimplementedSSHKeysServer) testEmbeddedByValue()                 {}

// UnsafeSSHKeysServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SSHKeysServer will
// result in compilation errors.
type UnsafeSSHKeysServer interface {
	mustEmbedUnimplementedSSHKeysServer()
}

func RegisterSSHKeysServer(s grpc.ServiceRegistrar, srv SSHKeysServer) {
	// If the following call pancis, it indicates UnimplementedSSHKeysServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SSHKeys_ServiceDesc, srv)
}

func _SSHKeys_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SSHKeysListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SSHKeysServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SSHKeys_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SSHKeysServer).List(ctx, req.(*SSHKeysListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SSHKeys_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SSHKeysGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SSHKeysServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SSHKeys_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SSHKeysServer).Get(ctx, req.(*SSHKeysGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SSHKeys_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SSHKeysCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SSHKeysServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SSHKeys_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SSHKeysServer).Create(ctx, req.(*SSHKeysCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SSHKeys_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SSHKeysUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SSHKeysServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SSHKeys_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SSHKeysServer).Update(ctx, req.(*SSHKeysUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SSHKeys_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SSHKeysDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SSHKeysServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SSHKeys_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SSHKeysServer).Delete(ctx, req.(*SSHKeysDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SSHKeys_Signal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SSHKeysSignalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SSHKeysServer).Signal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SSHKeys_Signal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SSHKeysServer).Signal(ctx, req.(*SSHKeysSignalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SSHKeys_ServiceDesc is the grpc.ServiceDesc for SSHKeys service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SSHKeys_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "osac.private.v1.SSHKeys",
	HandlerType: (*SSHKeysServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _SSHKeys_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _SSHKeys_Get_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _SSHKeys_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _SSHKeys_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _SSHKeys_Delete_Handler,
		},
		{
			MethodName: "Signal",
			Handler:    _SSHKeys_Signal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "osac/private/v1/ssh_keys_service.proto",
}
