//
// Copyright (c) 2026 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: osac/public/v1/compute_instance_group_type.proto

//go:build !protoopaque

package publicv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Lifecycle states for ComputeInstanceGroup resources.
type ComputeInstanceGroupState int32

const (
	ComputeInstanceGroupState_COMPUTE_INSTANCE_GROUP_STATE_UNSPECIFIED ComputeInstanceGroupState = 0
	ComputeInstanceGroupState_COMPUTE_INSTANCE_GROUP_STATE_PENDING     ComputeInstanceGroupState = 1
	ComputeInstanceGroupState_COMPUTE_INSTANCE_GROUP_STATE_READY       ComputeInstanceGroupState = 2
	ComputeInstanceGroupState_COMPUTE_INSTANCE_GROUP_STATE_SCALING     ComputeInstanceGroupState = 3
	ComputeInstanceGroupState_COMPUTE_INSTANCE_GROUP_STATE_FAILED      ComputeInstanceGroupState = 4
)

// Enum value maps for ComputeInstanceGroupState.
var (
	ComputeInstanceGroupState_name = map[int32]string{
		0: "COMPUTE_INSTANCE_GROUP_STATE_UNSPECIFIED",
		1: "COMPUTE_INSTANCE_GROUP_STATE_PENDING",
		2: "COMPUTE_INSTANCE_GROUP_STATE_READY",
		3: "COMPUTE_INSTANCE_GROUP_STATE_SCALING",
		4: "COMPUTE_INSTANCE_GROUP_STATE_FAILED",
	}
	ComputeInstanceGroupState_value = map[string]int32{
		"COMPUTE_INSTANCE_GROUP_STATE_UNSPECIFIED": 0,
		"COMPUTE_INSTANCE_GROUP_STATE_PENDING":     1,
		"COMPUTE_INSTANCE_GROUP_STATE_READY":       2,
		"COMPUTE_INSTANCE_GROUP_STATE_SCALING":     3,
		"COMPUTE_INSTANCE_GROUP_STATE_FAILED":      4,
	}
)

func (x ComputeInstanceGroupState) Enum() *ComputeInstanceGroupState {
	p := new(ComputeInstanceGroupState)
	*p = x
	return p
}

func (x ComputeInstanceGroupState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ComputeInstanceGroupState) Descriptor() protoreflect.EnumDescriptor {
	return file_osac_public_v1_compute_instance_group_type_proto_enumTypes[0].Descriptor()
}

func (ComputeInstanceGroupState) Type() protoreflect.EnumType {
	return &file_osac_public_v1_compute_instance_group_type_proto_enumTypes[0]
}

func (x ComputeInstanceGroupState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// A ComputeInstanceGroup manages a scaled set of identical ComputeInstances with placement semantics.
//
// ComputeInstanceGroup replaces the removed HostPool concept. It provides the same scaling semantics
// but works with both virtual and bare-metal compute through the unified ComputeInstanceClass model.
//
// Users create a group by specifying a ComputeInstanceClass and desired replica count. The system
// creates and manages individual ComputeInstance resources. Scaling up increases replicas, scaling
// down removes instances (last created first).
type ComputeInstanceGroup struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Unique identifier of the compute instance group.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Metadata of the compute instance group.
	Metadata *Metadata `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Desired state of the compute instance group.
	Spec *ComputeInstanceGroupSpec `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`
	// Current state of the compute instance group.
	Status        *ComputeInstanceGroupStatus `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComputeInstanceGroup) Reset() {
	*x = ComputeInstanceGroup{}
	mi := &file_osac_public_v1_compute_instance_group_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeInstanceGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeInstanceGroup) ProtoMessage() {}

func (x *ComputeInstanceGroup) ProtoReflect() protoreflect.Message {
	mi := &file_osac_public_v1_compute_instance_group_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ComputeInstanceGroup) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ComputeInstanceGroup) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ComputeInstanceGroup) GetSpec() *ComputeInstanceGroupSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *ComputeInstanceGroup) GetStatus() *ComputeInstanceGroupStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ComputeInstanceGroup) SetId(v string) {
	x.Id = v
}

func (x *ComputeInstanceGroup) SetMetadata(v *Metadata) {
	x.Metadata = v
}

func (x *ComputeInstanceGroup) SetSpec(v *ComputeInstanceGroupSpec) {
	x.Spec = v
}

func (x *ComputeInstanceGroup) SetStatus(v *ComputeInstanceGroupStatus) {
	x.Status = v
}

func (x *ComputeInstanceGroup) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.Metadata != nil
}

func (x *ComputeInstanceGroup) HasSpec() bool {
	if x == nil {
		return false
	}
	return x.Spec != nil
}

func (x *ComputeInstanceGroup) HasStatus() bool {
	if x == nil {
		return false
	}
	return x.Status != nil
}

func (x *ComputeInstanceGroup) ClearMetadata() {
	x.Metadata = nil
}

func (x *ComputeInstanceGroup) ClearSpec() {
	x.Spec = nil
}

func (x *ComputeInstanceGroup) ClearStatus() {
	x.Status = nil
}

type ComputeInstanceGroup_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Unique identifier of the compute instance group.
	Id string
	// Metadata of the compute instance group.
	Metadata *Metadata
	// Desired state of the compute instance group.
	Spec *ComputeInstanceGroupSpec
	// Current state of the compute instance group.
	Status *ComputeInstanceGroupStatus
}

func (b0 ComputeInstanceGroup_builder) Build() *ComputeInstanceGroup {
	m0 := &ComputeInstanceGroup{}
	b, x := &b0, m0
	_, _ = b, x
	x.Id = b.Id
	x.Metadata = b.Metadata
	x.Spec = b.Spec
	x.Status = b.Status
	return m0
}

// The spec contains the desired state of a compute instance group.
type ComputeInstanceGroupSpec struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Reference to the ComputeInstanceClass for all instances in this group.
	ComputeInstanceClass string `protobuf:"bytes,1,opt,name=compute_instance_class,json=computeInstanceClass,proto3" json:"compute_instance_class,omitempty"`
	// Desired number of ComputeInstances in the group.
	Replicas int32 `protobuf:"varint,2,opt,name=replicas,proto3" json:"replicas,omitempty"`
	// Reference to an Image resource by name.
	ImageRef *string `protobuf:"bytes,3,opt,name=image_ref,json=imageRef,proto3,oneof" json:"image_ref,omitempty"`
	// References to SSHKey resources by name.
	SshKeyRefs []string `protobuf:"bytes,4,rep,name=ssh_key_refs,json=sshKeyRefs,proto3" json:"ssh_key_refs,omitempty"`
	// Subnet ID for network attachment.
	Subnet *string `protobuf:"bytes,5,opt,name=subnet,proto3,oneof" json:"subnet,omitempty"`
	// SecurityGroup IDs for security policies.
	SecurityGroups []string `protobuf:"bytes,6,rep,name=security_groups,json=securityGroups,proto3" json:"security_groups,omitempty"`
	// User data for all instances in the group.
	UserData *string `protobuf:"bytes,7,opt,name=user_data,json=userData,proto3,oneof" json:"user_data,omitempty"`
	// Region narrows template selection within the class.
	Region *string `protobuf:"bytes,8,opt,name=region,proto3,oneof" json:"region,omitempty"`
	// Placement policy for instance distribution.
	PlacementPolicy *ComputeInstanceGroupPlacementPolicy `protobuf:"bytes,9,opt,name=placement_policy,json=placementPolicy,proto3,oneof" json:"placement_policy,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ComputeInstanceGroupSpec) Reset() {
	*x = ComputeInstanceGroupSpec{}
	mi := &file_osac_public_v1_compute_instance_group_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeInstanceGroupSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeInstanceGroupSpec) ProtoMessage() {}

func (x *ComputeInstanceGroupSpec) ProtoReflect() protoreflect.Message {
	mi := &file_osac_public_v1_compute_instance_group_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ComputeInstanceGroupSpec) GetComputeInstanceClass() string {
	if x != nil {
		return x.ComputeInstanceClass
	}
	return ""
}

func (x *ComputeInstanceGroupSpec) GetReplicas() int32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

func (x *ComputeInstanceGroupSpec) GetImageRef() string {
	if x != nil && x.ImageRef != nil {
		return *x.ImageRef
	}
	return ""
}

func (x *ComputeInstanceGroupSpec) GetSshKeyRefs() []string {
	if x != nil {
		return x.SshKeyRefs
	}
	return nil
}

func (x *ComputeInstanceGroupSpec) GetSubnet() string {
	if x != nil && x.Subnet != nil {
		return *x.Subnet
	}
	return ""
}

func (x *ComputeInstanceGroupSpec) GetSecurityGroups() []string {
	if x != nil {
		return x.SecurityGroups
	}
	return nil
}

func (x *ComputeInstanceGroupSpec) GetUserData() string {
	if x != nil && x.UserData != nil {
		return *x.UserData
	}
	return ""
}

func (x *ComputeInstanceGroupSpec) GetRegion() string {
	if x != nil && x.Region != nil {
		return *x.Region
	}
	return ""
}

func (x *ComputeInstanceGroupSpec) GetPlacementPolicy() *ComputeInstanceGroupPlacementPolicy {
	if x != nil {
		return x.PlacementPolicy
	}
	return nil
}

func (x *ComputeInstanceGroupSpec) SetComputeInstanceClass(v string) {
	x.ComputeInstanceClass = v
}

func (x *ComputeInstanceGroupSpec) SetReplicas(v int32) {
	x.Replicas = v
}

func (x *ComputeInstanceGroupSpec) SetImageRef(v string) {
	x.ImageRef = &v
}

func (x *ComputeInstanceGroupSpec) SetSshKeyRefs(v []string) {
	x.SshKeyRefs = v
}

func (x *ComputeInstanceGroupSpec) SetSubnet(v string) {
	x.Subnet = &v
}

func (x *ComputeInstanceGroupSpec) SetSecurityGroups(v []string) {
	x.SecurityGroups = v
}

func (x *ComputeInstanceGroupSpec) SetUserData(v string) {
	x.UserData = &v
}

func (x *ComputeInstanceGroupSpec) SetRegion(v string) {
	x.Region = &v
}

func (x *ComputeInstanceGroupSpec) SetPlacementPolicy(v *ComputeInstanceGroupPlacementPolicy) {
	x.PlacementPolicy = v
}

func (x *ComputeInstanceGroupSpec) HasImageRef() bool {
	if x == nil {
		return false
	}
	return x.ImageRef != nil
}

func (x *ComputeInstanceGroupSpec) HasSubnet() bool {
	if x == nil {
		return false
	}
	return x.Subnet != nil
}

func (x *ComputeInstanceGroupSpec) HasUserData() bool {
	if x == nil {
		return false
	}
	return x.UserData != nil
}

func (x *ComputeInstanceGroupSpec) HasRegion() bool {
	if x == nil {
		return false
	}
	return x.Region != nil
}

func (x *ComputeInstanceGroupSpec) HasPlacementPolicy() bool {
	if x == nil {
		return false
	}
	return x.PlacementPolicy != nil
}

func (x *ComputeInstanceGroupSpec) ClearImageRef() {
	x.ImageRef = nil
}

func (x *ComputeInstanceGroupSpec) ClearSubnet() {
	x.Subnet = nil
}

func (x *ComputeInstanceGroupSpec) ClearUserData() {
	x.UserData = nil
}

func (x *ComputeInstanceGroupSpec) ClearRegion() {
	x.Region = nil
}

func (x *ComputeInstanceGroupSpec) ClearPlacementPolicy() {
	x.PlacementPolicy = nil
}

type ComputeInstanceGroupSpec_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Reference to the ComputeInstanceClass for all instances in this group.
	ComputeInstanceClass string
	// Desired number of ComputeInstances in the group.
	Replicas int32
	// Reference to an Image resource by name.
	ImageRef *string
	// References to SSHKey resources by name.
	SshKeyRefs []string
	// Subnet ID for network attachment.
	Subnet *string
	// SecurityGroup IDs for security policies.
	SecurityGroups []string
	// User data for all instances in the group.
	UserData *string
	// Region narrows template selection within the class.
	Region *string
	// Placement policy for instance distribution.
	PlacementPolicy *ComputeInstanceGroupPlacementPolicy
}

func (b0 ComputeInstanceGroupSpec_builder) Build() *ComputeInstanceGroupSpec {
	m0 := &ComputeInstanceGroupSpec{}
	b, x := &b0, m0
	_, _ = b, x
	x.ComputeInstanceClass = b.ComputeInstanceClass
	x.Replicas = b.Replicas
	x.ImageRef = b.ImageRef
	x.SshKeyRefs = b.SshKeyRefs
	x.Subnet = b.Subnet
	x.SecurityGroups = b.SecurityGroups
	x.UserData = b.UserData
	x.Region = b.Region
	x.PlacementPolicy = b.PlacementPolicy
	return m0
}

// Placement policy controls how instances are distributed across infrastructure.
type ComputeInstanceGroupPlacementPolicy struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Strategy for placement: "pack" fills groups before spilling, "spread" distributes across domains.
	Strategy string `protobuf:"bytes,1,opt,name=strategy,proto3" json:"strategy,omitempty"`
	// Host variable name to group by for affinity (e.g. "nvlink_domain", "rack").
	AffinityKey   *string `protobuf:"bytes,2,opt,name=affinity_key,json=affinityKey,proto3,oneof" json:"affinity_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComputeInstanceGroupPlacementPolicy) Reset() {
	*x = ComputeInstanceGroupPlacementPolicy{}
	mi := &file_osac_public_v1_compute_instance_group_type_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeInstanceGroupPlacementPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeInstanceGroupPlacementPolicy) ProtoMessage() {}

func (x *ComputeInstanceGroupPlacementPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_osac_public_v1_compute_instance_group_type_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ComputeInstanceGroupPlacementPolicy) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *ComputeInstanceGroupPlacementPolicy) GetAffinityKey() string {
	if x != nil && x.AffinityKey != nil {
		return *x.AffinityKey
	}
	return ""
}

func (x *ComputeInstanceGroupPlacementPolicy) SetStrategy(v string) {
	x.Strategy = v
}

func (x *ComputeInstanceGroupPlacementPolicy) SetAffinityKey(v string) {
	x.AffinityKey = &v
}

func (x *ComputeInstanceGroupPlacementPolicy) HasAffinityKey() bool {
	if x == nil {
		return false
	}
	return x.AffinityKey != nil
}

func (x *ComputeInstanceGroupPlacementPolicy) ClearAffinityKey() {
	x.AffinityKey = nil
}

type ComputeInstanceGroupPlacementPolicy_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Strategy for placement: "pack" fills groups before spilling, "spread" distributes across domains.
	Strategy string
	// Host variable name to group by for affinity (e.g. "nvlink_domain", "rack").
	AffinityKey *string
}

func (b0 ComputeInstanceGroupPlacementPolicy_builder) Build() *ComputeInstanceGroupPlacementPolicy {
	m0 := &ComputeInstanceGroupPlacementPolicy{}
	b, x := &b0, m0
	_, _ = b, x
	x.Strategy = b.Strategy
	x.AffinityKey = b.AffinityKey
	return m0
}

// The status contains the current state of a compute instance group.
type ComputeInstanceGroupStatus struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Current lifecycle state of the group.
	State ComputeInstanceGroupState `protobuf:"varint,1,opt,name=state,proto3,enum=osac.public.v1.ComputeInstanceGroupState" json:"state,omitempty"`
	// Number of instances that are in RUNNING state.
	ReadyReplicas int32 `protobuf:"varint,2,opt,name=ready_replicas,json=readyReplicas,proto3" json:"ready_replicas,omitempty"`
	// List of ComputeInstance IDs managed by this group.
	Instances []string `protobuf:"bytes,3,rep,name=instances,proto3" json:"instances,omitempty"`
	// Human-readable message providing additional details about the current state.
	Message       *string `protobuf:"bytes,4,opt,name=message,proto3,oneof" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComputeInstanceGroupStatus) Reset() {
	*x = ComputeInstanceGroupStatus{}
	mi := &file_osac_public_v1_compute_instance_group_type_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeInstanceGroupStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeInstanceGroupStatus) ProtoMessage() {}

func (x *ComputeInstanceGroupStatus) ProtoReflect() protoreflect.Message {
	mi := &file_osac_public_v1_compute_instance_group_type_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ComputeInstanceGroupStatus) GetState() ComputeInstanceGroupState {
	if x != nil {
		return x.State
	}
	return ComputeInstanceGroupState_COMPUTE_INSTANCE_GROUP_STATE_UNSPECIFIED
}

func (x *ComputeInstanceGroupStatus) GetReadyReplicas() int32 {
	if x != nil {
		return x.ReadyReplicas
	}
	return 0
}

func (x *ComputeInstanceGroupStatus) GetInstances() []string {
	if x != nil {
		return x.Instances
	}
	return nil
}

func (x *ComputeInstanceGroupStatus) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *ComputeInstanceGroupStatus) SetState(v ComputeInstanceGroupState) {
	x.State = v
}

func (x *ComputeInstanceGroupStatus) SetReadyReplicas(v int32) {
	x.ReadyReplicas = v
}

func (x *ComputeInstanceGroupStatus) SetInstances(v []string) {
	x.Instances = v
}

func (x *ComputeInstanceGroupStatus) SetMessage(v string) {
	x.Message = &v
}

func (x *ComputeInstanceGroupStatus) HasMessage() bool {
	if x == nil {
		return false
	}
	return x.Message != nil
}

func (x *ComputeInstanceGroupStatus) ClearMessage() {
	x.Message = nil
}

type ComputeInstanceGroupStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Current lifecycle state of the group.
	State ComputeInstanceGroupState
	// Number of instances that are in RUNNING state.
	ReadyReplicas int32
	// List of ComputeInstance IDs managed by this group.
	Instances []string
	// Human-readable message providing additional details about the current state.
	Message *string
}

func (b0 ComputeInstanceGroupStatus_builder) Build() *ComputeInstanceGroupStatus {
	m0 := &ComputeInstanceGroupStatus{}
	b, x := &b0, m0
	_, _ = b, x
	x.State = b.State
	x.ReadyReplicas = b.ReadyReplicas
	x.Instances = b.Instances
	x.Message = b.Message
	return m0
}

var File_osac_public_v1_compute_instance_group_type_proto protoreflect.FileDescriptor

var file_osac_public_v1_compute_instance_group_type_proto_rawDesc = string([]byte{
	0x0a, 0x30, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2f, 0x76, 0x31,
	0x2f, 0x63, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x5f, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e,
	0x76, 0x31, 0x1a, 0x22, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2f,
	0x76, 0x31, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xde, 0x01, 0x0a, 0x14, 0x43, 0x6f, 0x6d, 0x70, 0x75,
	0x74, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x34, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e,
	0x76, 0x31, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x3c, 0x0a, 0x04, 0x73, 0x70, 0x65, 0x63, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x49, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x53, 0x70, 0x65, 0x63, 0x52, 0x04, 0x73,
	0x70, 0x65, 0x63, 0x12, 0x42, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x49, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0xe1, 0x03, 0x0a, 0x18, 0x43, 0x6f, 0x6d, 0x70,
	0x75, 0x74, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x53, 0x70, 0x65, 0x63, 0x12, 0x34, 0x0a, 0x16, 0x63, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x5f,
	0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x14, 0x63, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x49, 0x6e, 0x73,
	0x74, 0x61, 0x6e, 0x63, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65,
	0x70, 0x6c, 0x69, 0x63, 0x61, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x72, 0x65,
	0x70, 0x6c, 0x69, 0x63, 0x61, 0x73, 0x12, 0x20, 0x0a, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f,
	0x72, 0x65, 0x66, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x08, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x52, 0x65, 0x66, 0x88, 0x01, 0x01, 0x12, 0x20, 0x0a, 0x0c, 0x73, 0x73, 0x68, 0x5f,
	0x6b, 0x65, 0x79, 0x5f, 0x72, 0x65, 0x66, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a,
	0x73, 0x73, 0x68, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x66, 0x73, 0x12, 0x1b, 0x0a, 0x06, 0x73, 0x75,
	0x62, 0x6e, 0x65, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x06, 0x73, 0x75,
	0x62, 0x6e, 0x65, 0x74, 0x88, 0x01, 0x01, 0x12, 0x27, 0x0a, 0x0f, 0x73, 0x65, 0x63, 0x75, 0x72,
	0x69, 0x74, 0x79, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x0e, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73,
	0x12, 0x20, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x88,
	0x01, 0x01, 0x12, 0x1b, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x03, 0x52, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x12,
	0x63, 0x0a, 0x10, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x70, 0x6f, 0x6c,
	0x69, 0x63, 0x79, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x33, 0x2e, 0x6f, 0x73, 0x61, 0x63,
	0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x75,
	0x74, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x50,
	0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x48, 0x04,
	0x52, 0x0f, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x50, 0x6f, 0x6c, 0x69, 0x63,
	0x79, 0x88, 0x01, 0x01, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x72,
	0x65, 0x66, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x73, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x42, 0x0c, 0x0a,
	0x0a, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x42, 0x09, 0x0a, 0x07, 0x5f,
	0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x42, 0x13, 0x0a, 0x11, 0x5f, 0x70, 0x6c, 0x61, 0x63, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x22, 0x7a, 0x0a, 0x23, 0x43,
	0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x50, 0x6f, 0x6c, 0x69,
	0x63, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x12, 0x26,
	0x0a, 0x0c, 0x61, 0x66, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x79, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x61, 0x66, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x79,
	0x4b, 0x65, 0x79, 0x88, 0x01, 0x01, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x61, 0x66, 0x66, 0x69, 0x6e,
	0x69, 0x74, 0x79, 0x5f, 0x6b, 0x65, 0x79, 0x22, 0xcd, 0x01, 0x0a, 0x1a, 0x43, 0x6f, 0x6d, 0x70,
	0x75, 0x74, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x3f, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x29, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x49, 0x6e,
	0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x72, 0x65, 0x61, 0x64, 0x79,
	0x5f, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0d, 0x72, 0x65, 0x61, 0x64, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x73, 0x12, 0x1c,
	0x0a, 0x09, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x09, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x12, 0x1d, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x88, 0x01, 0x01, 0x42, 0x0a, 0x0a, 0x08, 0x5f,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2a, 0xee, 0x01, 0x0a, 0x19, 0x43, 0x6f, 0x6d, 0x70,
	0x75, 0x74, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x2c, 0x0a, 0x28, 0x43, 0x4f, 0x4d, 0x50, 0x55, 0x54, 0x45,
	0x5f, 0x49, 0x4e, 0x53, 0x54, 0x41, 0x4e, 0x43, 0x45, 0x5f, 0x47, 0x52, 0x4f, 0x55, 0x50, 0x5f,
	0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45,
	0x44, 0x10, 0x00, 0x12, 0x28, 0x0a, 0x24, 0x43, 0x4f, 0x4d, 0x50, 0x55, 0x54, 0x45, 0x5f, 0x49,
	0x4e, 0x53, 0x54, 0x41, 0x4e, 0x43, 0x45, 0x5f, 0x47, 0x52, 0x4f, 0x55, 0x50, 0x5f, 0x53, 0x54,
	0x41, 0x54, 0x45, 0x5f, 0x50, 0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x26, 0x0a,
	0x22, 0x43, 0x4f, 0x4d, 0x50, 0x55, 0x54, 0x45, 0x5f, 0x49, 0x4e, 0x53, 0x54, 0x41, 0x4e, 0x43,
	0x45, 0x5f, 0x47, 0x52, 0x4f, 0x55, 0x50, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x52, 0x45,
	0x41, 0x44, 0x59, 0x10, 0x02, 0x12, 0x28, 0x0a, 0x24, 0x43, 0x4f, 0x4d, 0x50, 0x55, 0x54, 0x45,
	0x5f, 0x49, 0x4e, 0x53, 0x54, 0x41, 0x4e, 0x43, 0x45, 0x5f, 0x47, 0x52, 0x4f, 0x55, 0x50, 0x5f,
	0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x53, 0x43, 0x41, 0x4c, 0x49, 0x4e, 0x47, 0x10, 0x03, 0x12,
	0x27, 0x0a, 0x23, 0x43, 0x4f, 0x4d, 0x50, 0x55, 0x54, 0x45, 0x5f, 0x49, 0x4e, 0x53, 0x54, 0x41,
	0x4e, 0x43, 0x45, 0x5f, 0x47, 0x52, 0x4f, 0x55, 0x50, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f,
	0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x04, 0x42, 0xe1, 0x01, 0x0a, 0x12, 0x63, 0x6f, 0x6d,
	0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x76, 0x31, 0x42,
	0x1d, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x54, 0x79, 0x70, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01,
	0x5a, 0x50, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x73, 0x61,
	0x63, 0x2d, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2f, 0x66, 0x75, 0x6c, 0x66, 0x69, 0x6c,
	0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x73, 0x61, 0x63, 0x2f,
	0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2f, 0x76, 0x31, 0x3b, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x76, 0x31, 0xa2, 0x02, 0x03, 0x4f, 0x50, 0x58, 0xaa, 0x02, 0x0e, 0x4f, 0x73, 0x61, 0x63, 0x2e,
	0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x0f, 0x4f, 0x73, 0x61, 0x63,
	0x5c, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x1b, 0x4f, 0x73,
	0x61, 0x63, 0x5c, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50,
	0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x10, 0x4f, 0x73, 0x61, 0x63,
	0x3a, 0x3a, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
})

var file_osac_public_v1_compute_instance_group_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_osac_public_v1_compute_instance_group_type_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_osac_public_v1_compute_instance_group_type_proto_goTypes = []any{
	(ComputeInstanceGroupState)(0),              // 0: osac.public.v1.ComputeInstanceGroupState
	(*ComputeInstanceGroup)(nil),                // 1: osac.public.v1.ComputeInstanceGroup
	(*ComputeInstanceGroupSpec)(nil),            // 2: osac.public.v1.ComputeInstanceGroupSpec
	(*ComputeInstanceGroupPlacementPolicy)(nil), // 3: osac.public.v1.ComputeInstanceGroupPlacementPolicy
	(*ComputeInstanceGroupStatus)(nil),          // 4: osac.public.v1.ComputeInstanceGroupStatus
	(*Metadata)(nil),                            // 5: osac.public.v1.Metadata
}
var file_osac_public_v1_compute_instance_group_type_proto_depIdxs = []int32{
	5, // 0: osac.public.v1.ComputeInstanceGroup.metadata:type_name -> osac.public.v1.Metadata
	2, // 1: osac.public.v1.ComputeInstanceGroup.spec:type_name -> osac.public.v1.ComputeInstanceGroupSpec
	4, // 2: osac.public.v1.ComputeInstanceGroup.status:type_name -> osac.public.v1.ComputeInstanceGroupStatus
	3, // 3: osac.public.v1.ComputeInstanceGroupSpec.placement_policy:type_name -> osac.public.v1.ComputeInstanceGroupPlacementPolicy
	0, // 4: osac.public.v1.ComputeInstanceGroupStatus.state:type_name -> osac.public.v1.ComputeInstanceGroupState
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_osac_public_v1_compute_instance_group_type_proto_init() }
func file_osac_public_v1_compute_instance_group_type_proto_init() {
	if File_osac_public_v1_compute_instance_group_type_proto != nil {
		return
	}
	file_osac_public_v1_metadata_type_proto_init()
	file_osac_public_v1_compute_instance_group_type_proto_msgTypes[1].OneofWrappers = []any{}
	file_osac_public_v1_compute_instance_group_type_proto_msgTypes[2].OneofWrappers = []any{}
	file_osac_public_v1_compute_instance_group_type_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_osac_public_v1_compute_instance_group_type_proto_rawDesc), len(file_osac_public_v1_compute_instance_group_type_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_osac_public_v1_compute_instance_group_type_proto_goTypes,
		DependencyIndexes: file_osac_public_v1_compute_instance_group_type_proto_depIdxs,
		EnumInfos:         file_osac_public_v1_compute_instance_group_type_proto_enumTypes,
		MessageInfos:      file_osac_public_v1_compute_instance_group_type_proto_msgTypes,
	}.Build()
	File_osac_public_v1_compute_instance_group_type_proto = out.File
	file_osac_public_v1_compute_instance_group_type_proto_goTypes = nil
	file_osac_public_v1_compute_instance_group_type_proto_depIdxs = nil
}
