//
// Copyright (c) 2026 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: osac/public/v1/compute_instance_class_type.proto

//go:build protoopaque

package publicv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Lifecycle states for ComputeInstanceClass resources.
type ComputeInstanceClassState int32

const (
	// State is unknown or has not been determined yet.
	ComputeInstanceClassState_COMPUTE_INSTANCE_CLASS_STATE_UNSPECIFIED ComputeInstanceClassState = 0
	// The compute instance class is being initialized and is not yet ready for use.
	ComputeInstanceClassState_COMPUTE_INSTANCE_CLASS_STATE_PENDING ComputeInstanceClassState = 1
	// The compute instance class is fully operational and available for creating ComputeInstances.
	ComputeInstanceClassState_COMPUTE_INSTANCE_CLASS_STATE_READY ComputeInstanceClassState = 2
	// The compute instance class has encountered an error and cannot be used for creating ComputeInstances.
	ComputeInstanceClassState_COMPUTE_INSTANCE_CLASS_STATE_FAILED ComputeInstanceClassState = 3
)

// Enum value maps for ComputeInstanceClassState.
var (
	ComputeInstanceClassState_name = map[int32]string{
		0: "COMPUTE_INSTANCE_CLASS_STATE_UNSPECIFIED",
		1: "COMPUTE_INSTANCE_CLASS_STATE_PENDING",
		2: "COMPUTE_INSTANCE_CLASS_STATE_READY",
		3: "COMPUTE_INSTANCE_CLASS_STATE_FAILED",
	}
	ComputeInstanceClassState_value = map[string]int32{
		"COMPUTE_INSTANCE_CLASS_STATE_UNSPECIFIED": 0,
		"COMPUTE_INSTANCE_CLASS_STATE_PENDING":     1,
		"COMPUTE_INSTANCE_CLASS_STATE_READY":       2,
		"COMPUTE_INSTANCE_CLASS_STATE_FAILED":      3,
	}
)

func (x ComputeInstanceClassState) Enum() *ComputeInstanceClassState {
	p := new(ComputeInstanceClassState)
	*p = x
	return p
}

func (x ComputeInstanceClassState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ComputeInstanceClassState) Descriptor() protoreflect.EnumDescriptor {
	return file_osac_public_v1_compute_instance_class_type_proto_enumTypes[0].Descriptor()
}

func (ComputeInstanceClassState) Type() protoreflect.EnumType {
	return &file_osac_public_v1_compute_instance_class_type_proto_enumTypes[0]
}

func (x ComputeInstanceClassState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Describes a provider-defined SKU or catalog entry for compute offerings.
//
// ComputeInstanceClass represents a specific compute offering that tenants can order. For example,
// there could be a compute instance class `bm-large` describing a bare metal server with 64 cores
// and 256 GiB of memory, or `vm-small` describing a virtual machine with 2 cores and 4 GiB of memory.
//
// This is similar to the _instance type_ concept used by cloud providers (e.g., AWS m5.xlarge),
// or the _storage class_ concept used by Kubernetes for persistent volumes.
//
// Users query available ComputeInstanceClasses to discover which compute offerings they can choose
// when creating ComputeInstances.
type ComputeInstanceClass struct {
	state                   protoimpl.MessageState              `protogen:"opaque.v1"`
	xxx_hidden_Id           string                              `protobuf:"bytes,1,opt,name=id,proto3"`
	xxx_hidden_Metadata     *Metadata                           `protobuf:"bytes,2,opt,name=metadata,proto3"`
	xxx_hidden_Title        string                              `protobuf:"bytes,3,opt,name=title,proto3"`
	xxx_hidden_Description  string                              `protobuf:"bytes,4,opt,name=description,proto3"`
	xxx_hidden_Backend      string                              `protobuf:"bytes,5,opt,name=backend,proto3"`
	xxx_hidden_Capabilities *ComputeInstanceClassCapabilities   `protobuf:"bytes,6,opt,name=capabilities,proto3"`
	xxx_hidden_Templates    *[]*ComputeInstanceClassTemplateRef `protobuf:"bytes,7,rep,name=templates,proto3"`
	xxx_hidden_Status       *ComputeInstanceClassStatus         `protobuf:"bytes,8,opt,name=status,proto3"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ComputeInstanceClass) Reset() {
	*x = ComputeInstanceClass{}
	mi := &file_osac_public_v1_compute_instance_class_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeInstanceClass) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeInstanceClass) ProtoMessage() {}

func (x *ComputeInstanceClass) ProtoReflect() protoreflect.Message {
	mi := &file_osac_public_v1_compute_instance_class_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ComputeInstanceClass) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *ComputeInstanceClass) GetMetadata() *Metadata {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return nil
}

func (x *ComputeInstanceClass) GetTitle() string {
	if x != nil {
		return x.xxx_hidden_Title
	}
	return ""
}

func (x *ComputeInstanceClass) GetDescription() string {
	if x != nil {
		return x.xxx_hidden_Description
	}
	return ""
}

func (x *ComputeInstanceClass) GetBackend() string {
	if x != nil {
		return x.xxx_hidden_Backend
	}
	return ""
}

func (x *ComputeInstanceClass) GetCapabilities() *ComputeInstanceClassCapabilities {
	if x != nil {
		return x.xxx_hidden_Capabilities
	}
	return nil
}

func (x *ComputeInstanceClass) GetTemplates() []*ComputeInstanceClassTemplateRef {
	if x != nil {
		if x.xxx_hidden_Templates != nil {
			return *x.xxx_hidden_Templates
		}
	}
	return nil
}

func (x *ComputeInstanceClass) GetStatus() *ComputeInstanceClassStatus {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return nil
}

func (x *ComputeInstanceClass) SetId(v string) {
	x.xxx_hidden_Id = v
}

func (x *ComputeInstanceClass) SetMetadata(v *Metadata) {
	x.xxx_hidden_Metadata = v
}

func (x *ComputeInstanceClass) SetTitle(v string) {
	x.xxx_hidden_Title = v
}

func (x *ComputeInstanceClass) SetDescription(v string) {
	x.xxx_hidden_Description = v
}

func (x *ComputeInstanceClass) SetBackend(v string) {
	x.xxx_hidden_Backend = v
}

func (x *ComputeInstanceClass) SetCapabilities(v *ComputeInstanceClassCapabilities) {
	x.xxx_hidden_Capabilities = v
}

func (x *ComputeInstanceClass) SetTemplates(v []*ComputeInstanceClassTemplateRef) {
	x.xxx_hidden_Templates = &v
}

func (x *ComputeInstanceClass) SetStatus(v *ComputeInstanceClassStatus) {
	x.xxx_hidden_Status = v
}

func (x *ComputeInstanceClass) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Metadata != nil
}

func (x *ComputeInstanceClass) HasCapabilities() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Capabilities != nil
}

func (x *ComputeInstanceClass) HasStatus() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Status != nil
}

func (x *ComputeInstanceClass) ClearMetadata() {
	x.xxx_hidden_Metadata = nil
}

func (x *ComputeInstanceClass) ClearCapabilities() {
	x.xxx_hidden_Capabilities = nil
}

func (x *ComputeInstanceClass) ClearStatus() {
	x.xxx_hidden_Status = nil
}

type ComputeInstanceClass_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Unique identifier of the compute instance class.
	Id string
	// Metadata of the compute instance class.
	Metadata *Metadata
	// Human friendly short description of the compute instance class, only a few words, suitable for displaying in one
	// single line on a UI or CLI. For example: "Large Bare Metal" or "Small Virtual Machine".
	Title string
	// Human friendly long description of the compute instance class, using Markdown format. This should explain the
	// characteristics of compute instances created using this class, including performance characteristics,
	// hardware specifications, and any limitations or requirements.
	Description string
	// Backend provisioning type for this class. For example: "baremetal" or "virtual".
	Backend string
	// Capabilities that this compute instance class provides. These describe what compute resources are available
	// when using this class.
	Capabilities *ComputeInstanceClassCapabilities
	// References to the templates that can fulfill this class. Each template reference identifies a specific
	// Ansible role at a specific site that can provision compute instances of this class.
	Templates []*ComputeInstanceClassTemplateRef
	// Current operational status of the compute instance class.
	Status *ComputeInstanceClassStatus
}

func (b0 ComputeInstanceClass_builder) Build() *ComputeInstanceClass {
	m0 := &ComputeInstanceClass{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Metadata = b.Metadata
	x.xxx_hidden_Title = b.Title
	x.xxx_hidden_Description = b.Description
	x.xxx_hidden_Backend = b.Backend
	x.xxx_hidden_Capabilities = b.Capabilities
	x.xxx_hidden_Templates = &b.Templates
	x.xxx_hidden_Status = b.Status
	return m0
}

// Describes the compute capabilities provided by a ComputeInstanceClass.
//
// Fields use a fixed/min/max pattern: if a value is fixed, the tenant gets exactly that amount;
// if min/max are set, the tenant can choose within that range.
type ComputeInstanceClassCapabilities struct {
	state                     protoimpl.MessageState       `protogen:"opaque.v1"`
	xxx_hidden_CoresFixed     int32                        `protobuf:"varint,1,opt,name=cores_fixed,json=coresFixed,proto3,oneof"`
	xxx_hidden_CoresMin       int32                        `protobuf:"varint,2,opt,name=cores_min,json=coresMin,proto3,oneof"`
	xxx_hidden_CoresMax       int32                        `protobuf:"varint,3,opt,name=cores_max,json=coresMax,proto3,oneof"`
	xxx_hidden_MemoryGibFixed int32                        `protobuf:"varint,4,opt,name=memory_gib_fixed,json=memoryGibFixed,proto3,oneof"`
	xxx_hidden_MemoryGibMin   int32                        `protobuf:"varint,5,opt,name=memory_gib_min,json=memoryGibMin,proto3,oneof"`
	xxx_hidden_MemoryGibMax   int32                        `protobuf:"varint,6,opt,name=memory_gib_max,json=memoryGibMax,proto3,oneof"`
	xxx_hidden_Gpus           *ComputeInstanceClassGPU     `protobuf:"bytes,7,opt,name=gpus,proto3,oneof"`
	xxx_hidden_Storage        *ComputeInstanceClassStorage `protobuf:"bytes,8,opt,name=storage,proto3,oneof"`
	XXX_raceDetectHookData    protoimpl.RaceDetectHookData
	XXX_presence              [1]uint32
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ComputeInstanceClassCapabilities) Reset() {
	*x = ComputeInstanceClassCapabilities{}
	mi := &file_osac_public_v1_compute_instance_class_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeInstanceClassCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeInstanceClassCapabilities) ProtoMessage() {}

func (x *ComputeInstanceClassCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_osac_public_v1_compute_instance_class_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ComputeInstanceClassCapabilities) GetCoresFixed() int32 {
	if x != nil {
		return x.xxx_hidden_CoresFixed
	}
	return 0
}

func (x *ComputeInstanceClassCapabilities) GetCoresMin() int32 {
	if x != nil {
		return x.xxx_hidden_CoresMin
	}
	return 0
}

func (x *ComputeInstanceClassCapabilities) GetCoresMax() int32 {
	if x != nil {
		return x.xxx_hidden_CoresMax
	}
	return 0
}

func (x *ComputeInstanceClassCapabilities) GetMemoryGibFixed() int32 {
	if x != nil {
		return x.xxx_hidden_MemoryGibFixed
	}
	return 0
}

func (x *ComputeInstanceClassCapabilities) GetMemoryGibMin() int32 {
	if x != nil {
		return x.xxx_hidden_MemoryGibMin
	}
	return 0
}

func (x *ComputeInstanceClassCapabilities) GetMemoryGibMax() int32 {
	if x != nil {
		return x.xxx_hidden_MemoryGibMax
	}
	return 0
}

func (x *ComputeInstanceClassCapabilities) GetGpus() *ComputeInstanceClassGPU {
	if x != nil {
		return x.xxx_hidden_Gpus
	}
	return nil
}

func (x *ComputeInstanceClassCapabilities) GetStorage() *ComputeInstanceClassStorage {
	if x != nil {
		return x.xxx_hidden_Storage
	}
	return nil
}

func (x *ComputeInstanceClassCapabilities) SetCoresFixed(v int32) {
	x.xxx_hidden_CoresFixed = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 8)
}

func (x *ComputeInstanceClassCapabilities) SetCoresMin(v int32) {
	x.xxx_hidden_CoresMin = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 8)
}

func (x *ComputeInstanceClassCapabilities) SetCoresMax(v int32) {
	x.xxx_hidden_CoresMax = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 8)
}

func (x *ComputeInstanceClassCapabilities) SetMemoryGibFixed(v int32) {
	x.xxx_hidden_MemoryGibFixed = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 8)
}

func (x *ComputeInstanceClassCapabilities) SetMemoryGibMin(v int32) {
	x.xxx_hidden_MemoryGibMin = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 8)
}

func (x *ComputeInstanceClassCapabilities) SetMemoryGibMax(v int32) {
	x.xxx_hidden_MemoryGibMax = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 8)
}

func (x *ComputeInstanceClassCapabilities) SetGpus(v *ComputeInstanceClassGPU) {
	x.xxx_hidden_Gpus = v
}

func (x *ComputeInstanceClassCapabilities) SetStorage(v *ComputeInstanceClassStorage) {
	x.xxx_hidden_Storage = v
}

func (x *ComputeInstanceClassCapabilities) HasCoresFixed() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ComputeInstanceClassCapabilities) HasCoresMin() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ComputeInstanceClassCapabilities) HasCoresMax() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ComputeInstanceClassCapabilities) HasMemoryGibFixed() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *ComputeInstanceClassCapabilities) HasMemoryGibMin() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *ComputeInstanceClassCapabilities) HasMemoryGibMax() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *ComputeInstanceClassCapabilities) HasGpus() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Gpus != nil
}

func (x *ComputeInstanceClassCapabilities) HasStorage() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Storage != nil
}

func (x *ComputeInstanceClassCapabilities) ClearCoresFixed() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_CoresFixed = 0
}

func (x *ComputeInstanceClassCapabilities) ClearCoresMin() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_CoresMin = 0
}

func (x *ComputeInstanceClassCapabilities) ClearCoresMax() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_CoresMax = 0
}

func (x *ComputeInstanceClassCapabilities) ClearMemoryGibFixed() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_MemoryGibFixed = 0
}

func (x *ComputeInstanceClassCapabilities) ClearMemoryGibMin() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_MemoryGibMin = 0
}

func (x *ComputeInstanceClassCapabilities) ClearMemoryGibMax() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_MemoryGibMax = 0
}

func (x *ComputeInstanceClassCapabilities) ClearGpus() {
	x.xxx_hidden_Gpus = nil
}

func (x *ComputeInstanceClassCapabilities) ClearStorage() {
	x.xxx_hidden_Storage = nil
}

type ComputeInstanceClassCapabilities_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fixed number of CPU cores. If set, the tenant gets exactly this many cores.
	CoresFixed *int32
	// Minimum number of CPU cores the tenant can request.
	CoresMin *int32
	// Maximum number of CPU cores the tenant can request.
	CoresMax *int32
	// Fixed amount of memory in GiB. If set, the tenant gets exactly this much memory.
	MemoryGibFixed *int32
	// Minimum amount of memory in GiB the tenant can request.
	MemoryGibMin *int32
	// Maximum amount of memory in GiB the tenant can request.
	MemoryGibMax *int32
	// GPU capabilities, if any.
	Gpus *ComputeInstanceClassGPU
	// Storage capabilities.
	Storage *ComputeInstanceClassStorage
}

func (b0 ComputeInstanceClassCapabilities_builder) Build() *ComputeInstanceClassCapabilities {
	m0 := &ComputeInstanceClassCapabilities{}
	b, x := &b0, m0
	_, _ = b, x
	if b.CoresFixed != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 8)
		x.xxx_hidden_CoresFixed = *b.CoresFixed
	}
	if b.CoresMin != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 8)
		x.xxx_hidden_CoresMin = *b.CoresMin
	}
	if b.CoresMax != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 8)
		x.xxx_hidden_CoresMax = *b.CoresMax
	}
	if b.MemoryGibFixed != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 8)
		x.xxx_hidden_MemoryGibFixed = *b.MemoryGibFixed
	}
	if b.MemoryGibMin != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 8)
		x.xxx_hidden_MemoryGibMin = *b.MemoryGibMin
	}
	if b.MemoryGibMax != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 8)
		x.xxx_hidden_MemoryGibMax = *b.MemoryGibMax
	}
	x.xxx_hidden_Gpus = b.Gpus
	x.xxx_hidden_Storage = b.Storage
	return m0
}

// Describes GPU capabilities of a ComputeInstanceClass.
type ComputeInstanceClassGPU struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Count int32                  `protobuf:"varint,1,opt,name=count,proto3"`
	xxx_hidden_Model string                 `protobuf:"bytes,2,opt,name=model,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ComputeInstanceClassGPU) Reset() {
	*x = ComputeInstanceClassGPU{}
	mi := &file_osac_public_v1_compute_instance_class_type_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeInstanceClassGPU) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeInstanceClassGPU) ProtoMessage() {}

func (x *ComputeInstanceClassGPU) ProtoReflect() protoreflect.Message {
	mi := &file_osac_public_v1_compute_instance_class_type_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ComputeInstanceClassGPU) GetCount() int32 {
	if x != nil {
		return x.xxx_hidden_Count
	}
	return 0
}

func (x *ComputeInstanceClassGPU) GetModel() string {
	if x != nil {
		return x.xxx_hidden_Model
	}
	return ""
}

func (x *ComputeInstanceClassGPU) SetCount(v int32) {
	x.xxx_hidden_Count = v
}

func (x *ComputeInstanceClassGPU) SetModel(v string) {
	x.xxx_hidden_Model = v
}

type ComputeInstanceClassGPU_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Number of GPUs available.
	Count int32
	// GPU model identifier. For example: "nvidia-a100", "nvidia-h100".
	Model string
}

func (b0 ComputeInstanceClassGPU_builder) Build() *ComputeInstanceClassGPU {
	m0 := &ComputeInstanceClassGPU{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Count = b.Count
	x.xxx_hidden_Model = b.Model
	return m0
}

// Describes storage capabilities of a ComputeInstanceClass.
type ComputeInstanceClassStorage struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_BootDiskGibFixed int32                  `protobuf:"varint,1,opt,name=boot_disk_gib_fixed,json=bootDiskGibFixed,proto3,oneof"`
	xxx_hidden_BootDiskGibMin   int32                  `protobuf:"varint,2,opt,name=boot_disk_gib_min,json=bootDiskGibMin,proto3,oneof"`
	xxx_hidden_BootDiskGibMax   int32                  `protobuf:"varint,3,opt,name=boot_disk_gib_max,json=bootDiskGibMax,proto3,oneof"`
	XXX_raceDetectHookData      protoimpl.RaceDetectHookData
	XXX_presence                [1]uint32
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *ComputeInstanceClassStorage) Reset() {
	*x = ComputeInstanceClassStorage{}
	mi := &file_osac_public_v1_compute_instance_class_type_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeInstanceClassStorage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeInstanceClassStorage) ProtoMessage() {}

func (x *ComputeInstanceClassStorage) ProtoReflect() protoreflect.Message {
	mi := &file_osac_public_v1_compute_instance_class_type_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ComputeInstanceClassStorage) GetBootDiskGibFixed() int32 {
	if x != nil {
		return x.xxx_hidden_BootDiskGibFixed
	}
	return 0
}

func (x *ComputeInstanceClassStorage) GetBootDiskGibMin() int32 {
	if x != nil {
		return x.xxx_hidden_BootDiskGibMin
	}
	return 0
}

func (x *ComputeInstanceClassStorage) GetBootDiskGibMax() int32 {
	if x != nil {
		return x.xxx_hidden_BootDiskGibMax
	}
	return 0
}

func (x *ComputeInstanceClassStorage) SetBootDiskGibFixed(v int32) {
	x.xxx_hidden_BootDiskGibFixed = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *ComputeInstanceClassStorage) SetBootDiskGibMin(v int32) {
	x.xxx_hidden_BootDiskGibMin = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *ComputeInstanceClassStorage) SetBootDiskGibMax(v int32) {
	x.xxx_hidden_BootDiskGibMax = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *ComputeInstanceClassStorage) HasBootDiskGibFixed() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ComputeInstanceClassStorage) HasBootDiskGibMin() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ComputeInstanceClassStorage) HasBootDiskGibMax() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ComputeInstanceClassStorage) ClearBootDiskGibFixed() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_BootDiskGibFixed = 0
}

func (x *ComputeInstanceClassStorage) ClearBootDiskGibMin() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_BootDiskGibMin = 0
}

func (x *ComputeInstanceClassStorage) ClearBootDiskGibMax() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_BootDiskGibMax = 0
}

type ComputeInstanceClassStorage_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fixed boot disk size in GiB.
	BootDiskGibFixed *int32
	// Minimum boot disk size in GiB the tenant can request.
	BootDiskGibMin *int32
	// Maximum boot disk size in GiB the tenant can request.
	BootDiskGibMax *int32
}

func (b0 ComputeInstanceClassStorage_builder) Build() *ComputeInstanceClassStorage {
	m0 := &ComputeInstanceClassStorage{}
	b, x := &b0, m0
	_, _ = b, x
	if b.BootDiskGibFixed != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_BootDiskGibFixed = *b.BootDiskGibFixed
	}
	if b.BootDiskGibMin != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_BootDiskGibMin = *b.BootDiskGibMin
	}
	if b.BootDiskGibMax != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_BootDiskGibMax = *b.BootDiskGibMax
	}
	return m0
}

// Reference to a ComputeInstanceTemplate that can fulfill this class.
type ComputeInstanceClassTemplateRef struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name string                 `protobuf:"bytes,1,opt,name=name,proto3"`
	xxx_hidden_Site string                 `protobuf:"bytes,2,opt,name=site,proto3"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ComputeInstanceClassTemplateRef) Reset() {
	*x = ComputeInstanceClassTemplateRef{}
	mi := &file_osac_public_v1_compute_instance_class_type_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeInstanceClassTemplateRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeInstanceClassTemplateRef) ProtoMessage() {}

func (x *ComputeInstanceClassTemplateRef) ProtoReflect() protoreflect.Message {
	mi := &file_osac_public_v1_compute_instance_class_type_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ComputeInstanceClassTemplateRef) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *ComputeInstanceClassTemplateRef) GetSite() string {
	if x != nil {
		return x.xxx_hidden_Site
	}
	return ""
}

func (x *ComputeInstanceClassTemplateRef) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *ComputeInstanceClassTemplateRef) SetSite(v string) {
	x.xxx_hidden_Site = v
}

type ComputeInstanceClassTemplateRef_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Name of the template.
	Name string
	// Site where this template is available.
	Site string
}

func (b0 ComputeInstanceClassTemplateRef_builder) Build() *ComputeInstanceClassTemplateRef {
	m0 := &ComputeInstanceClassTemplateRef{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Site = b.Site
	return m0
}

// Represents the current operational state of a ComputeInstanceClass.
type ComputeInstanceClassStatus struct {
	state                  protoimpl.MessageState    `protogen:"opaque.v1"`
	xxx_hidden_State       ComputeInstanceClassState `protobuf:"varint,1,opt,name=state,proto3,enum=osac.public.v1.ComputeInstanceClassState"`
	xxx_hidden_Message     *string                   `protobuf:"bytes,2,opt,name=message,proto3,oneof"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ComputeInstanceClassStatus) Reset() {
	*x = ComputeInstanceClassStatus{}
	mi := &file_osac_public_v1_compute_instance_class_type_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeInstanceClassStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeInstanceClassStatus) ProtoMessage() {}

func (x *ComputeInstanceClassStatus) ProtoReflect() protoreflect.Message {
	mi := &file_osac_public_v1_compute_instance_class_type_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ComputeInstanceClassStatus) GetState() ComputeInstanceClassState {
	if x != nil {
		return x.xxx_hidden_State
	}
	return ComputeInstanceClassState_COMPUTE_INSTANCE_CLASS_STATE_UNSPECIFIED
}

func (x *ComputeInstanceClassStatus) GetMessage() string {
	if x != nil {
		if x.xxx_hidden_Message != nil {
			return *x.xxx_hidden_Message
		}
		return ""
	}
	return ""
}

func (x *ComputeInstanceClassStatus) SetState(v ComputeInstanceClassState) {
	x.xxx_hidden_State = v
}

func (x *ComputeInstanceClassStatus) SetMessage(v string) {
	x.xxx_hidden_Message = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *ComputeInstanceClassStatus) HasMessage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ComputeInstanceClassStatus) ClearMessage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Message = nil
}

type ComputeInstanceClassStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Current lifecycle state of the compute instance class.
	State ComputeInstanceClassState
	// Human-readable message providing additional details about the current state. For example, if the state is
	// FAILED, this message might explain what went wrong.
	Message *string
}

func (b0 ComputeInstanceClassStatus_builder) Build() *ComputeInstanceClassStatus {
	m0 := &ComputeInstanceClassStatus{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_State = b.State
	if b.Message != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Message = b.Message
	}
	return m0
}

var File_osac_public_v1_compute_instance_class_type_proto protoreflect.FileDescriptor

var file_osac_public_v1_compute_instance_class_type_proto_rawDesc = string([]byte{
	0x0a, 0x30, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2f, 0x76, 0x31,
	0x2f, 0x63, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x5f, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x5f, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e,
	0x76, 0x31, 0x1a, 0x22, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2f,
	0x76, 0x31, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x97, 0x03, 0x0a, 0x14, 0x43, 0x6f, 0x6d, 0x70, 0x75,
	0x74, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x34, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e,
	0x76, 0x31, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a,
	0x07, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x12, 0x54, 0x0a, 0x0c, 0x63, 0x61, 0x70, 0x61, 0x62,
	0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x30, 0x2e,
	0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x43,
	0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x43, 0x6c,
	0x61, 0x73, 0x73, 0x43, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x52,
	0x0c, 0x63, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x12, 0x4d, 0x0a,
	0x09, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x2f, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x76,
	0x31, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x66, 0x52, 0x09, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x12, 0x42, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x6f,
	0x73, 0x61, 0x63, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f,
	0x6d, 0x70, 0x75, 0x74, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x43, 0x6c, 0x61,
	0x73, 0x73, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x22, 0x9b, 0x04, 0x0a, 0x20, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x49, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x43, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c,
	0x69, 0x74, 0x69, 0x65, 0x73, 0x12, 0x24, 0x0a, 0x0b, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x5f, 0x66,
	0x69, 0x78, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x0a, 0x63, 0x6f,
	0x72, 0x65, 0x73, 0x46, 0x69, 0x78, 0x65, 0x64, 0x88, 0x01, 0x01, 0x12, 0x20, 0x0a, 0x09, 0x63,
	0x6f, 0x72, 0x65, 0x73, 0x5f, 0x6d, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x48, 0x01,
	0x52, 0x08, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x4d, 0x69, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x20, 0x0a,
	0x09, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x5f, 0x6d, 0x61, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x48, 0x02, 0x52, 0x08, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x4d, 0x61, 0x78, 0x88, 0x01, 0x01, 0x12,
	0x2d, 0x0a, 0x10, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x5f, 0x67, 0x69, 0x62, 0x5f, 0x66, 0x69,
	0x78, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x48, 0x03, 0x52, 0x0e, 0x6d, 0x65, 0x6d,
	0x6f, 0x72, 0x79, 0x47, 0x69, 0x62, 0x46, 0x69, 0x78, 0x65, 0x64, 0x88, 0x01, 0x01, 0x12, 0x29,
	0x0a, 0x0e, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x5f, 0x67, 0x69, 0x62, 0x5f, 0x6d, 0x69, 0x6e,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x48, 0x04, 0x52, 0x0c, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79,
	0x47, 0x69, 0x62, 0x4d, 0x69, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x29, 0x0a, 0x0e, 0x6d, 0x65, 0x6d,
	0x6f, 0x72, 0x79, 0x5f, 0x67, 0x69, 0x62, 0x5f, 0x6d, 0x61, 0x78, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x05, 0x48, 0x05, 0x52, 0x0c, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x47, 0x69, 0x62, 0x4d, 0x61,
	0x78, 0x88, 0x01, 0x01, 0x12, 0x40, 0x0a, 0x04, 0x67, 0x70, 0x75, 0x73, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x27, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x47, 0x50, 0x55, 0x48, 0x06, 0x52, 0x04, 0x67,
	0x70, 0x75, 0x73, 0x88, 0x01, 0x01, 0x12, 0x4a, 0x0a, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65,
	0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x53, 0x74, 0x6f,
	0x72, 0x61, 0x67, 0x65, 0x48, 0x07, 0x52, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x88,
	0x01, 0x01, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x5f, 0x66, 0x69, 0x78,
	0x65, 0x64, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x5f, 0x6d, 0x69, 0x6e,
	0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x5f, 0x6d, 0x61, 0x78, 0x42, 0x13,
	0x0a, 0x11, 0x5f, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x5f, 0x67, 0x69, 0x62, 0x5f, 0x66, 0x69,
	0x78, 0x65, 0x64, 0x42, 0x11, 0x0a, 0x0f, 0x5f, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x5f, 0x67,
	0x69, 0x62, 0x5f, 0x6d, 0x69, 0x6e, 0x42, 0x11, 0x0a, 0x0f, 0x5f, 0x6d, 0x65, 0x6d, 0x6f, 0x72,
	0x79, 0x5f, 0x67, 0x69, 0x62, 0x5f, 0x6d, 0x61, 0x78, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x67, 0x70,
	0x75, 0x73, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x22, 0x45,
	0x0a, 0x17, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x47, 0x50, 0x55, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0xf5, 0x01, 0x0a, 0x1b, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74,
	0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x53, 0x74,
	0x6f, 0x72, 0x61, 0x67, 0x65, 0x12, 0x32, 0x0a, 0x13, 0x62, 0x6f, 0x6f, 0x74, 0x5f, 0x64, 0x69,
	0x73, 0x6b, 0x5f, 0x67, 0x69, 0x62, 0x5f, 0x66, 0x69, 0x78, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x48, 0x00, 0x52, 0x10, 0x62, 0x6f, 0x6f, 0x74, 0x44, 0x69, 0x73, 0x6b, 0x47, 0x69,
	0x62, 0x46, 0x69, 0x78, 0x65, 0x64, 0x88, 0x01, 0x01, 0x12, 0x2e, 0x0a, 0x11, 0x62, 0x6f, 0x6f,
	0x74, 0x5f, 0x64, 0x69, 0x73, 0x6b, 0x5f, 0x67, 0x69, 0x62, 0x5f, 0x6d, 0x69, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x48, 0x01, 0x52, 0x0e, 0x62, 0x6f, 0x6f, 0x74, 0x44, 0x69, 0x73, 0x6b,
	0x47, 0x69, 0x62, 0x4d, 0x69, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x2e, 0x0a, 0x11, 0x62, 0x6f, 0x6f,
	0x74, 0x5f, 0x64, 0x69, 0x73, 0x6b, 0x5f, 0x67, 0x69, 0x62, 0x5f, 0x6d, 0x61, 0x78, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x48, 0x02, 0x52, 0x0e, 0x62, 0x6f, 0x6f, 0x74, 0x44, 0x69, 0x73, 0x6b,
	0x47, 0x69, 0x62, 0x4d, 0x61, 0x78, 0x88, 0x01, 0x01, 0x42, 0x16, 0x0a, 0x14, 0x5f, 0x62, 0x6f,
	0x6f, 0x74, 0x5f, 0x64, 0x69, 0x73, 0x6b, 0x5f, 0x67, 0x69, 0x62, 0x5f, 0x66, 0x69, 0x78, 0x65,
	0x64, 0x42, 0x14, 0x0a, 0x12, 0x5f, 0x62, 0x6f, 0x6f, 0x74, 0x5f, 0x64, 0x69, 0x73, 0x6b, 0x5f,
	0x67, 0x69, 0x62, 0x5f, 0x6d, 0x69, 0x6e, 0x42, 0x14, 0x0a, 0x12, 0x5f, 0x62, 0x6f, 0x6f, 0x74,
	0x5f, 0x64, 0x69, 0x73, 0x6b, 0x5f, 0x67, 0x69, 0x62, 0x5f, 0x6d, 0x61, 0x78, 0x22, 0x49, 0x0a,
	0x1f, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x43, 0x6c, 0x61, 0x73, 0x73, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x66,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x73, 0x69, 0x74, 0x65, 0x22, 0x88, 0x01, 0x0a, 0x1a, 0x43, 0x6f, 0x6d,
	0x70, 0x75, 0x74, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x43, 0x6c, 0x61, 0x73,
	0x73, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x3f, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x29, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x49,
	0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1d, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x88, 0x01, 0x01, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2a, 0xc4, 0x01, 0x0a, 0x19, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x49,
	0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x12, 0x2c, 0x0a, 0x28, 0x43, 0x4f, 0x4d, 0x50, 0x55, 0x54, 0x45, 0x5f, 0x49, 0x4e, 0x53,
	0x54, 0x41, 0x4e, 0x43, 0x45, 0x5f, 0x43, 0x4c, 0x41, 0x53, 0x53, 0x5f, 0x53, 0x54, 0x41, 0x54,
	0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12,
	0x28, 0x0a, 0x24, 0x43, 0x4f, 0x4d, 0x50, 0x55, 0x54, 0x45, 0x5f, 0x49, 0x4e, 0x53, 0x54, 0x41,
	0x4e, 0x43, 0x45, 0x5f, 0x43, 0x4c, 0x41, 0x53, 0x53, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f,
	0x50, 0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x26, 0x0a, 0x22, 0x43, 0x4f, 0x4d,
	0x50, 0x55, 0x54, 0x45, 0x5f, 0x49, 0x4e, 0x53, 0x54, 0x41, 0x4e, 0x43, 0x45, 0x5f, 0x43, 0x4c,
	0x41, 0x53, 0x53, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x52, 0x45, 0x41, 0x44, 0x59, 0x10,
	0x02, 0x12, 0x27, 0x0a, 0x23, 0x43, 0x4f, 0x4d, 0x50, 0x55, 0x54, 0x45, 0x5f, 0x49, 0x4e, 0x53,
	0x54, 0x41, 0x4e, 0x43, 0x45, 0x5f, 0x43, 0x4c, 0x41, 0x53, 0x53, 0x5f, 0x53, 0x54, 0x41, 0x54,
	0x45, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x03, 0x42, 0xe1, 0x01, 0x0a, 0x12, 0x63,
	0x6f, 0x6d, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x76,
	0x31, 0x42, 0x1d, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e,
	0x63, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x54, 0x79, 0x70, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x50, 0x01, 0x5a, 0x50, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f,
	0x73, 0x61, 0x63, 0x2d, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2f, 0x66, 0x75, 0x6c, 0x66,
	0x69, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x73, 0x61,
	0x63, 0x2f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2f, 0x76, 0x31, 0x3b, 0x70, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x4f, 0x50, 0x58, 0xaa, 0x02, 0x0e, 0x4f, 0x73, 0x61,
	0x63, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x0f, 0x4f, 0x73,
	0x61, 0x63, 0x5c, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x1b,
	0x4f, 0x73, 0x61, 0x63, 0x5c, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x5c, 0x56, 0x31, 0x5c,
	0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x10, 0x4f, 0x73,
	0x61, 0x63, 0x3a, 0x3a, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var file_osac_public_v1_compute_instance_class_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_osac_public_v1_compute_instance_class_type_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_osac_public_v1_compute_instance_class_type_proto_goTypes = []any{
	(ComputeInstanceClassState)(0),           // 0: osac.public.v1.ComputeInstanceClassState
	(*ComputeInstanceClass)(nil),             // 1: osac.public.v1.ComputeInstanceClass
	(*ComputeInstanceClassCapabilities)(nil), // 2: osac.public.v1.ComputeInstanceClassCapabilities
	(*ComputeInstanceClassGPU)(nil),          // 3: osac.public.v1.ComputeInstanceClassGPU
	(*ComputeInstanceClassStorage)(nil),      // 4: osac.public.v1.ComputeInstanceClassStorage
	(*ComputeInstanceClassTemplateRef)(nil),  // 5: osac.public.v1.ComputeInstanceClassTemplateRef
	(*ComputeInstanceClassStatus)(nil),       // 6: osac.public.v1.ComputeInstanceClassStatus
	(*Metadata)(nil),                         // 7: osac.public.v1.Metadata
}
var file_osac_public_v1_compute_instance_class_type_proto_depIdxs = []int32{
	7, // 0: osac.public.v1.ComputeInstanceClass.metadata:type_name -> osac.public.v1.Metadata
	2, // 1: osac.public.v1.ComputeInstanceClass.capabilities:type_name -> osac.public.v1.ComputeInstanceClassCapabilities
	5, // 2: osac.public.v1.ComputeInstanceClass.templates:type_name -> osac.public.v1.ComputeInstanceClassTemplateRef
	6, // 3: osac.public.v1.ComputeInstanceClass.status:type_name -> osac.public.v1.ComputeInstanceClassStatus
	3, // 4: osac.public.v1.ComputeInstanceClassCapabilities.gpus:type_name -> osac.public.v1.ComputeInstanceClassGPU
	4, // 5: osac.public.v1.ComputeInstanceClassCapabilities.storage:type_name -> osac.public.v1.ComputeInstanceClassStorage
	0, // 6: osac.public.v1.ComputeInstanceClassStatus.state:type_name -> osac.public.v1.ComputeInstanceClassState
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_osac_public_v1_compute_instance_class_type_proto_init() }
func file_osac_public_v1_compute_instance_class_type_proto_init() {
	if File_osac_public_v1_compute_instance_class_type_proto != nil {
		return
	}
	file_osac_public_v1_metadata_type_proto_init()
	file_osac_public_v1_compute_instance_class_type_proto_msgTypes[1].OneofWrappers = []any{}
	file_osac_public_v1_compute_instance_class_type_proto_msgTypes[3].OneofWrappers = []any{}
	file_osac_public_v1_compute_instance_class_type_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_osac_public_v1_compute_instance_class_type_proto_rawDesc), len(file_osac_public_v1_compute_instance_class_type_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_osac_public_v1_compute_instance_class_type_proto_goTypes,
		DependencyIndexes: file_osac_public_v1_compute_instance_class_type_proto_depIdxs,
		EnumInfos:         file_osac_public_v1_compute_instance_class_type_proto_enumTypes,
		MessageInfos:      file_osac_public_v1_compute_instance_class_type_proto_msgTypes,
	}.Build()
	File_osac_public_v1_compute_instance_class_type_proto = out.File
	file_osac_public_v1_compute_instance_class_type_proto_goTypes = nil
	file_osac_public_v1_compute_instance_class_type_proto_depIdxs = nil
}
