//
// Copyright (c) 2025 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: osac/public/v1/image_type.proto

//go:build !protoopaque

package publicv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Lifecycle states for Image resources.
type ImageState int32

const (
	// State is unknown or has not been determined yet.
	ImageState_IMAGE_STATE_UNSPECIFIED ImageState = 0
	// The image is being initialized and is not yet ready for use.
	ImageState_IMAGE_STATE_PENDING ImageState = 1
	// The image is fully operational and available for creating ComputeInstances.
	ImageState_IMAGE_STATE_READY ImageState = 2
	// The image has encountered an error and cannot be used for creating ComputeInstances.
	ImageState_IMAGE_STATE_FAILED ImageState = 3
)

// Enum value maps for ImageState.
var (
	ImageState_name = map[int32]string{
		0: "IMAGE_STATE_UNSPECIFIED",
		1: "IMAGE_STATE_PENDING",
		2: "IMAGE_STATE_READY",
		3: "IMAGE_STATE_FAILED",
	}
	ImageState_value = map[string]int32{
		"IMAGE_STATE_UNSPECIFIED": 0,
		"IMAGE_STATE_PENDING":     1,
		"IMAGE_STATE_READY":       2,
		"IMAGE_STATE_FAILED":      3,
	}
)

func (x ImageState) Enum() *ImageState {
	p := new(ImageState)
	*p = x
	return p
}

func (x ImageState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ImageState) Descriptor() protoreflect.EnumDescriptor {
	return file_osac_public_v1_image_type_proto_enumTypes[0].Descriptor()
}

func (ImageState) Type() protoreflect.EnumType {
	return &file_osac_public_v1_image_type_proto_enumTypes[0]
}

func (x ImageState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Represents a bootable OS image in the provider's catalog.
//
// Image describes a bootable operating system image that can be used to provision ComputeInstances. Each image
// includes metadata about the operating system, architecture, and boot method, as well as a reference to the
// image source (e.g., an OCI registry URL).
//
// Images are provider-defined catalog resources. Users query available Images to discover which operating
// system options they can choose when creating ComputeInstances.
type Image struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Unique identifier of the image.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Metadata of the image.
	Metadata *Metadata `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Human friendly short description of the image, only a few words, suitable for displaying in one single
	// line on a UI or CLI. For example: "RHEL 9.4" or "Fedora CoreOS 40".
	Title string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	// Human friendly long description of the image, using Markdown format. This should explain the
	// characteristics of the image, including the operating system, version, and any special features
	// or requirements.
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// Type of image source. For example: "registry" for OCI container images.
	SourceType string `protobuf:"bytes,5,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	// Reference to the image source. For example, an OCI image URL like
	// "quay.io/openshift-release-dev/ocp-release:4.14.0-x86_64".
	SourceRef string `protobuf:"bytes,6,opt,name=source_ref,json=sourceRef,proto3" json:"source_ref,omitempty"`
	// Operating system name. For example: "rhel", "fedora", "centos".
	Os *string `protobuf:"bytes,7,opt,name=os,proto3,oneof" json:"os,omitempty"`
	// Operating system version. For example: "9.4", "40".
	Version *string `protobuf:"bytes,8,opt,name=version,proto3,oneof" json:"version,omitempty"`
	// CPU architecture. For example: "aarch64", "x86_64".
	Architecture *string `protobuf:"bytes,9,opt,name=architecture,proto3,oneof" json:"architecture,omitempty"`
	// Boot method used by the image. Valid values are "ignition", "cloud-init", "kickstart".
	BootMethod string `protobuf:"bytes,10,opt,name=boot_method,json=bootMethod,proto3" json:"boot_method,omitempty"`
	// List of ComputeInstanceClass IDs that this image is compatible with.
	Compatibility []string `protobuf:"bytes,11,rep,name=compatibility,proto3" json:"compatibility,omitempty"`
	// Current operational status of the image.
	Status        *ImageStatus `protobuf:"bytes,12,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Image) Reset() {
	*x = Image{}
	mi := &file_osac_public_v1_image_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_osac_public_v1_image_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Image) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Image) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Image) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Image) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Image) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *Image) GetSourceRef() string {
	if x != nil {
		return x.SourceRef
	}
	return ""
}

func (x *Image) GetOs() string {
	if x != nil && x.Os != nil {
		return *x.Os
	}
	return ""
}

func (x *Image) GetVersion() string {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return ""
}

func (x *Image) GetArchitecture() string {
	if x != nil && x.Architecture != nil {
		return *x.Architecture
	}
	return ""
}

func (x *Image) GetBootMethod() string {
	if x != nil {
		return x.BootMethod
	}
	return ""
}

func (x *Image) GetCompatibility() []string {
	if x != nil {
		return x.Compatibility
	}
	return nil
}

func (x *Image) GetStatus() *ImageStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *Image) SetId(v string) {
	x.Id = v
}

func (x *Image) SetMetadata(v *Metadata) {
	x.Metadata = v
}

func (x *Image) SetTitle(v string) {
	x.Title = v
}

func (x *Image) SetDescription(v string) {
	x.Description = v
}

func (x *Image) SetSourceType(v string) {
	x.SourceType = v
}

func (x *Image) SetSourceRef(v string) {
	x.SourceRef = v
}

func (x *Image) SetOs(v string) {
	x.Os = &v
}

func (x *Image) SetVersion(v string) {
	x.Version = &v
}

func (x *Image) SetArchitecture(v string) {
	x.Architecture = &v
}

func (x *Image) SetBootMethod(v string) {
	x.BootMethod = v
}

func (x *Image) SetCompatibility(v []string) {
	x.Compatibility = v
}

func (x *Image) SetStatus(v *ImageStatus) {
	x.Status = v
}

func (x *Image) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.Metadata != nil
}

func (x *Image) HasOs() bool {
	if x == nil {
		return false
	}
	return x.Os != nil
}

func (x *Image) HasVersion() bool {
	if x == nil {
		return false
	}
	return x.Version != nil
}

func (x *Image) HasArchitecture() bool {
	if x == nil {
		return false
	}
	return x.Architecture != nil
}

func (x *Image) HasStatus() bool {
	if x == nil {
		return false
	}
	return x.Status != nil
}

func (x *Image) ClearMetadata() {
	x.Metadata = nil
}

func (x *Image) ClearOs() {
	x.Os = nil
}

func (x *Image) ClearVersion() {
	x.Version = nil
}

func (x *Image) ClearArchitecture() {
	x.Architecture = nil
}

func (x *Image) ClearStatus() {
	x.Status = nil
}

type Image_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Unique identifier of the image.
	Id string
	// Metadata of the image.
	Metadata *Metadata
	// Human friendly short description of the image, only a few words, suitable for displaying in one single
	// line on a UI or CLI. For example: "RHEL 9.4" or "Fedora CoreOS 40".
	Title string
	// Human friendly long description of the image, using Markdown format. This should explain the
	// characteristics of the image, including the operating system, version, and any special features
	// or requirements.
	Description string
	// Type of image source. For example: "registry" for OCI container images.
	SourceType string
	// Reference to the image source. For example, an OCI image URL like
	// "quay.io/openshift-release-dev/ocp-release:4.14.0-x86_64".
	SourceRef string
	// Operating system name. For example: "rhel", "fedora", "centos".
	Os *string
	// Operating system version. For example: "9.4", "40".
	Version *string
	// CPU architecture. For example: "aarch64", "x86_64".
	Architecture *string
	// Boot method used by the image. Valid values are "ignition", "cloud-init", "kickstart".
	BootMethod string
	// List of ComputeInstanceClass IDs that this image is compatible with.
	Compatibility []string
	// Current operational status of the image.
	Status *ImageStatus
}

func (b0 Image_builder) Build() *Image {
	m0 := &Image{}
	b, x := &b0, m0
	_, _ = b, x
	x.Id = b.Id
	x.Metadata = b.Metadata
	x.Title = b.Title
	x.Description = b.Description
	x.SourceType = b.SourceType
	x.SourceRef = b.SourceRef
	x.Os = b.Os
	x.Version = b.Version
	x.Architecture = b.Architecture
	x.BootMethod = b.BootMethod
	x.Compatibility = b.Compatibility
	x.Status = b.Status
	return m0
}

// Represents the current operational state of an Image.
type ImageStatus struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Current lifecycle state of the image.
	State ImageState `protobuf:"varint,1,opt,name=state,proto3,enum=osac.public.v1.ImageState" json:"state,omitempty"`
	// Human-readable message providing additional details about the current state. For example, if the state is
	// FAILED, this message might explain what went wrong.
	Message       *string `protobuf:"bytes,2,opt,name=message,proto3,oneof" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageStatus) Reset() {
	*x = ImageStatus{}
	mi := &file_osac_public_v1_image_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageStatus) ProtoMessage() {}

func (x *ImageStatus) ProtoReflect() protoreflect.Message {
	mi := &file_osac_public_v1_image_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ImageStatus) GetState() ImageState {
	if x != nil {
		return x.State
	}
	return ImageState_IMAGE_STATE_UNSPECIFIED
}

func (x *ImageStatus) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *ImageStatus) SetState(v ImageState) {
	x.State = v
}

func (x *ImageStatus) SetMessage(v string) {
	x.Message = &v
}

func (x *ImageStatus) HasMessage() bool {
	if x == nil {
		return false
	}
	return x.Message != nil
}

func (x *ImageStatus) ClearMessage() {
	x.Message = nil
}

type ImageStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Current lifecycle state of the image.
	State ImageState
	// Human-readable message providing additional details about the current state. For example, if the state is
	// FAILED, this message might explain what went wrong.
	Message *string
}

func (b0 ImageStatus_builder) Build() *ImageStatus {
	m0 := &ImageStatus{}
	b, x := &b0, m0
	_, _ = b, x
	x.State = b.State
	x.Message = b.Message
	return m0
}

var File_osac_public_v1_image_type_proto protoreflect.FileDescriptor

var file_osac_public_v1_image_type_proto_rawDesc = string([]byte{
	0x0a, 0x1f, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2f, 0x76, 0x31,
	0x2f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x76,
	0x31, 0x1a, 0x22, 0x6f, 0x73, 0x61, 0x63, 0x2f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2f, 0x76,
	0x31, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc2, 0x03, 0x0a, 0x05, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x34, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e,
	0x76, 0x31, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x0a,
	0x0b, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1d,
	0x0a, 0x0a, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x72, 0x65, 0x66, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x66, 0x12, 0x13, 0x0a,
	0x02, 0x6f, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x02, 0x6f, 0x73, 0x88,
	0x01, 0x01, 0x12, 0x1d, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x88, 0x01,
	0x01, 0x12, 0x27, 0x0a, 0x0c, 0x61, 0x72, 0x63, 0x68, 0x69, 0x74, 0x65, 0x63, 0x74, 0x75, 0x72,
	0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x0c, 0x61, 0x72, 0x63, 0x68, 0x69,
	0x74, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x88, 0x01, 0x01, 0x12, 0x1f, 0x0a, 0x0b, 0x62, 0x6f,
	0x6f, 0x74, 0x5f, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x62, 0x6f, 0x6f, 0x74, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x63,
	0x6f, 0x6d, 0x70, 0x61, 0x74, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x18, 0x0b, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x74, 0x69, 0x62, 0x69, 0x6c, 0x69, 0x74,
	0x79, 0x12, 0x33, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x0c, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1b, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e,
	0x76, 0x31, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x05, 0x0a, 0x03, 0x5f, 0x6f, 0x73, 0x42, 0x0a, 0x0a,
	0x08, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x61, 0x72,
	0x63, 0x68, 0x69, 0x74, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x22, 0x6a, 0x0a, 0x0b, 0x49, 0x6d,
	0x61, 0x67, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x30, 0x0a, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e,
	0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1d, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x88, 0x01, 0x01, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2a, 0x71, 0x0a, 0x0a, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x12, 0x1b, 0x0a, 0x17, 0x49, 0x4d, 0x41, 0x47, 0x45, 0x5f, 0x53, 0x54,
	0x41, 0x54, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10,
	0x00, 0x12, 0x17, 0x0a, 0x13, 0x49, 0x4d, 0x41, 0x47, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45,
	0x5f, 0x50, 0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x15, 0x0a, 0x11, 0x49, 0x4d,
	0x41, 0x47, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x52, 0x45, 0x41, 0x44, 0x59, 0x10,
	0x02, 0x12, 0x16, 0x0a, 0x12, 0x49, 0x4d, 0x41, 0x47, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45,
	0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x03, 0x42, 0xd2, 0x01, 0x0a, 0x12, 0x63, 0x6f,
	0x6d, 0x2e, 0x6f, 0x73, 0x61, 0x63, 0x2e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x76, 0x31,
	0x42, 0x0e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x50, 0x01, 0x5a, 0x50, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f,
	0x73, 0x61, 0x63, 0x2d, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2f, 0x66, 0x75, 0x6c, 0x66,
	0x69, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x73, 0x61,
	0x63, 0x2f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2f, 0x76, 0x31, 0x3b, 0x70, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x4f, 0x50, 0x58, 0xaa, 0x02, 0x0e, 0x4f, 0x73, 0x61,
	0x63, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x0f, 0x4f, 0x73,
	0x61, 0x63, 0x5c, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x1b,
	0x4f, 0x73, 0x61, 0x63, 0x5c, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x5c, 0x56, 0x31, 0x5c,
	0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x10, 0x4f, 0x73,
	0x61, 0x63, 0x3a, 0x3a, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var file_osac_public_v1_image_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_osac_public_v1_image_type_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_osac_public_v1_image_type_proto_goTypes = []any{
	(ImageState)(0),     // 0: osac.public.v1.ImageState
	(*Image)(nil),       // 1: osac.public.v1.Image
	(*ImageStatus)(nil), // 2: osac.public.v1.ImageStatus
	(*Metadata)(nil),    // 3: osac.public.v1.Metadata
}
var file_osac_public_v1_image_type_proto_depIdxs = []int32{
	3, // 0: osac.public.v1.Image.metadata:type_name -> osac.public.v1.Metadata
	2, // 1: osac.public.v1.Image.status:type_name -> osac.public.v1.ImageStatus
	0, // 2: osac.public.v1.ImageStatus.state:type_name -> osac.public.v1.ImageState
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_osac_public_v1_image_type_proto_init() }
func file_osac_public_v1_image_type_proto_init() {
	if File_osac_public_v1_image_type_proto != nil {
		return
	}
	file_osac_public_v1_metadata_type_proto_init()
	file_osac_public_v1_image_type_proto_msgTypes[0].OneofWrappers = []any{}
	file_osac_public_v1_image_type_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_osac_public_v1_image_type_proto_rawDesc), len(file_osac_public_v1_image_type_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_osac_public_v1_image_type_proto_goTypes,
		DependencyIndexes: file_osac_public_v1_image_type_proto_depIdxs,
		EnumInfos:         file_osac_public_v1_image_type_proto_enumTypes,
		MessageInfos:      file_osac_public_v1_image_type_proto_msgTypes,
	}.Build()
	File_osac_public_v1_image_type_proto = out.File
	file_osac_public_v1_image_type_proto_goTypes = nil
	file_osac_public_v1_image_type_proto_depIdxs = nil
}
